<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>InteroceptionProfiles - Data Analysis (Emma)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="2_analysis_emma_files/libs/clipboard/clipboard.min.js"></script>
<script src="2_analysis_emma_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="2_analysis_emma_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="2_analysis_emma_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="2_analysis_emma_files/libs/quarto-html/popper.min.js"></script>
<script src="2_analysis_emma_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="2_analysis_emma_files/libs/quarto-html/anchor.min.js"></script>
<link href="2_analysis_emma_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="2_analysis_emma_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="2_analysis_emma_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="2_analysis_emma_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="2_analysis_emma_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#load-packages-and-data" id="toc-load-packages-and-data" class="nav-link active" data-scroll-target="#load-packages-and-data">1. Load packages and data</a></li>
  <li><a href="#compute-facet-metacluster-scores" id="toc-compute-facet-metacluster-scores" class="nav-link" data-scroll-target="#compute-facet-metacluster-scores">2. Compute Facet &amp; Metacluster Scores</a>
  <ul class="collapse">
  <li><a href="#item-labels" id="toc-item-labels" class="nav-link" data-scroll-target="#item-labels">2.1. Item Labels</a></li>
  </ul></li>
  <li><a href="#replicate-ega-from-interoceptionscale-study-2" id="toc-replicate-ega-from-interoceptionscale-study-2" class="nav-link" data-scroll-target="#replicate-ega-from-interoceptionscale-study-2">3. Replicate EGA from InteroceptionScale Study 2</a></li>
  <li><a href="#clustering" id="toc-clustering" class="nav-link" data-scroll-target="#clustering">4. Clustering</a>
  <ul class="collapse">
  <li><a href="#estimate-number-of-clusters" id="toc-estimate-number-of-clusters" class="nav-link" data-scroll-target="#estimate-number-of-clusters">4.1. Estimate Number of Clusters</a></li>
  <li><a href="#kmeans" id="toc-kmeans" class="nav-link" data-scroll-target="#kmeans">4.2. Kmeans</a></li>
  <li><a href="#hierarchical-clustering" id="toc-hierarchical-clustering" class="nav-link" data-scroll-target="#hierarchical-clustering">4.3. Hierarchical Clustering</a></li>
  <li><a href="#hierarchical-k-means" id="toc-hierarchical-k-means" class="nav-link" data-scroll-target="#hierarchical-k-means">4.4. Hierarchical K-Means</a></li>
  <li><a href="#k-medoids-pam" id="toc-k-medoids-pam" class="nav-link" data-scroll-target="#k-medoids-pam">4.5. K-Medoids (PAM)</a></li>
  <li><a href="#dbscan" id="toc-dbscan" class="nav-link" data-scroll-target="#dbscan">4.6. DBSCAN</a></li>
  <li><a href="#k-medoids-with-estimation-of-number-of-clusters-pamk" id="toc-k-medoids-with-estimation-of-number-of-clusters-pamk" class="nav-link" data-scroll-target="#k-medoids-with-estimation-of-number-of-clusters-pamk">4.7. K-Medoids with estimation of number of clusters (pamk)</a></li>
  <li><a href="#mixture" id="toc-mixture" class="nav-link" data-scroll-target="#mixture">4.8. Mixture</a></li>
  </ul></li>
  <li><a href="#metaclustering" id="toc-metaclustering" class="nav-link" data-scroll-target="#metaclustering">5. Metaclustering</a></li>
  <li><a href="#extract-participants-from-clusters" id="toc-extract-participants-from-clusters" class="nav-link" data-scroll-target="#extract-participants-from-clusters">6. Extract participants from clusters</a></li>
  <li><a href="#analysis" id="toc-analysis" class="nav-link" data-scroll-target="#analysis">7. Analysis</a>
  <ul class="collapse">
  <li><a href="#age" id="toc-age" class="nav-link" data-scroll-target="#age">7.1. Age</a></li>
  <li><a href="#depression-anxiety-phq-4" id="toc-depression-anxiety-phq-4" class="nav-link" data-scroll-target="#depression-anxiety-phq-4">7.2. Depression &amp; Anxiety (PHQ-4)</a></li>
  <li><a href="#gender" id="toc-gender" class="nav-link" data-scroll-target="#gender">7.3. Gender</a></li>
  <li><a href="#mental-health-conditions-diagnosed" id="toc-mental-health-conditions-diagnosed" class="nav-link" data-scroll-target="#mental-health-conditions-diagnosed">7.4. Mental Health Conditions (Diagnosed)</a>
  <ul class="collapse">
  <li><a href="#mood" id="toc-mood" class="nav-link" data-scroll-target="#mood">7.4.1. Mood</a></li>
  <li><a href="#anxiety" id="toc-anxiety" class="nav-link" data-scroll-target="#anxiety">7.4.2. Anxiety</a></li>
  <li><a href="#eating-disorders" id="toc-eating-disorders" class="nav-link" data-scroll-target="#eating-disorders">7.4.3. Eating Disorders</a></li>
  <li><a href="#autism" id="toc-autism" class="nav-link" data-scroll-target="#autism">7.4.4 Autism</a></li>
  <li><a href="#adhd" id="toc-adhd" class="nav-link" data-scroll-target="#adhd">7.4.5. ADHD</a></li>
  </ul></li>
  <li><a href="#somatic-health-conditions-diagnosed" id="toc-somatic-health-conditions-diagnosed" class="nav-link" data-scroll-target="#somatic-health-conditions-diagnosed">7.5. Somatic Health Conditions (Diagnosed)</a>
  <ul class="collapse">
  <li><a href="#afferent-sensitivity" id="toc-afferent-sensitivity" class="nav-link" data-scroll-target="#afferent-sensitivity">7.5.1. Afferent Sensitivity</a></li>
  <li><a href="#central-sensitisation" id="toc-central-sensitisation" class="nav-link" data-scroll-target="#central-sensitisation">7.5.2. Central Sensitisation</a></li>
  <li><a href="#autonomic-dysfunction" id="toc-autonomic-dysfunction" class="nav-link" data-scroll-target="#autonomic-dysfunction">7.5.3. Autonomic Dysfunction</a></li>
  <li><a href="#immune-inflammatory" id="toc-immune-inflammatory" class="nav-link" data-scroll-target="#immune-inflammatory">7.5.4. Immune-Inflammatory</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#multinomial-logistic-regression" id="toc-multinomial-logistic-regression" class="nav-link" data-scroll-target="#multinomial-logistic-regression">8. Multinomial Logistic Regression</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">InteroceptionProfiles - Data Analysis (Emma)</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="load-packages-and-data" class="level1">
<h1>1. Load packages and data</h1>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjmisc)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(cluster)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(factoextra)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mclust)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pvclust)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(NbClust)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dbscan)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kernlab)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(apcluster)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nnet)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(umap)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Rtsne)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(EGAnet)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggdist)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effectsize)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(easystats)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>mega_df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/EmmaLBenn/ChatExtracts/refs/heads/main/data/Emma_dissertationdata.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="compute-facet-metacluster-scores" class="level1">
<h1>2. Compute Facet &amp; Metacluster Scores</h1>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>mint_items <span class="ot">&lt;-</span> <span class="fu">select</span>(mega_df, <span class="fu">starts_with</span>(<span class="st">"MINT_"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>MINT_AttentionCheck)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Lower order facet scores (mean of 3 items each)</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>mega_df <span class="ot">&lt;-</span> mega_df <span class="sc">|&gt;</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Awareness metacluster</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">MINT_SexS  =</span> <span class="fu">rowMeans</span>(<span class="fu">across</span>(<span class="fu">starts_with</span>(<span class="st">"MINT_SexS_"</span>)),  <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">MINT_ExAc  =</span> <span class="fu">rowMeans</span>(<span class="fu">across</span>(<span class="fu">starts_with</span>(<span class="st">"MINT_ExAc_"</span>)),  <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">MINT_RelA  =</span> <span class="fu">rowMeans</span>(<span class="fu">across</span>(<span class="fu">starts_with</span>(<span class="st">"MINT_RelA_"</span>)),  <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Deficit metacluster</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">MINT_CaCo  =</span> <span class="fu">rowMeans</span>(<span class="fu">across</span>(<span class="fu">starts_with</span>(<span class="st">"MINT_CaCo_"</span>)),  <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">MINT_Urin  =</span> <span class="fu">rowMeans</span>(<span class="fu">across</span>(<span class="fu">starts_with</span>(<span class="st">"MINT_Urin_"</span>)),  <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">MINT_Derm  =</span> <span class="fu">rowMeans</span>(<span class="fu">across</span>(<span class="fu">starts_with</span>(<span class="st">"MINT_Derm_"</span>)),  <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">MINT_Sati  =</span> <span class="fu">rowMeans</span>(<span class="fu">across</span>(<span class="fu">starts_with</span>(<span class="st">"MINT_Sati_"</span>)),  <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">MINT_Olfa  =</span> <span class="fu">rowMeans</span>(<span class="fu">across</span>(<span class="fu">starts_with</span>(<span class="st">"MINT_Olfa_"</span>)),  <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Visceroception metacluster</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">MINT_Card  =</span> <span class="fu">rowMeans</span>(<span class="fu">across</span>(<span class="fu">starts_with</span>(<span class="st">"MINT_Card_"</span>)),  <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">MINT_Resp  =</span> <span class="fu">rowMeans</span>(<span class="fu">across</span>(<span class="fu">starts_with</span>(<span class="st">"MINT_Resp_"</span>)),  <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">MINT_Gast  =</span> <span class="fu">rowMeans</span>(<span class="fu">across</span>(<span class="fu">starts_with</span>(<span class="st">"MINT_Gast_"</span>)),  <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Higher order metacluster scores (mean of facets)</span></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>mega_df <span class="ot">&lt;-</span> mega_df <span class="sc">|&gt;</span></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">MINT_Awareness =</span> <span class="fu">rowMeans</span>(<span class="fu">across</span>(<span class="fu">c</span>(MINT_SexS, MINT_ExAc, MINT_RelA)), <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">MINT_Deficit =</span> <span class="fu">rowMeans</span>(<span class="fu">across</span>(<span class="fu">c</span>(MINT_CaCo, MINT_Urin, MINT_Derm, MINT_Sati, MINT_Olfa)), <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">MINT_Visceroception =</span> <span class="fu">rowMeans</span>(<span class="fu">across</span>(<span class="fu">c</span>(MINT_Card, MINT_Resp, MINT_Gast)), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>mint_lowerorder <span class="ot">&lt;-</span> mega_df <span class="sc">|&gt;</span> </span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(MINT_SexS, MINT_ExAc, MINT_RelA, MINT_CaCo, MINT_Urin, MINT_Derm, MINT_Sati, MINT_Olfa, MINT_Card, MINT_Resp, MINT_Gast)</span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a>mint_higherorder <span class="ot">&lt;-</span> mega_df <span class="sc">|&gt;</span> </span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(MINT_Awareness, MINT_Deficit, MINT_Visceroception)</span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Facet scores computed for N ="</span>, <span class="fu">nrow</span>(mega_df), <span class="st">"participants</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Facet scores computed for N = 1689 participants</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Sources included:"</span>, <span class="fu">paste</span>(<span class="fu">unique</span>(mega_df<span class="sc">$</span>Source), <span class="at">collapse =</span> <span class="st">", "</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Sources included: InteroceptionScale_Study1, InteroceptionScale_Study2, FakeArt, FakeChat </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Structure Validation</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(mint_items) <span class="ot">&lt;-</span> <span class="fu">str_remove</span>(<span class="fu">names</span>(mint_items), <span class="st">"MINT_"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<section id="item-labels" class="level2">
<h2 class="anchored" data-anchor-id="item-labels">2.1. Item Labels</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>labels <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">MINT_ExAc_1 =</span> </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"I can always accurately feel when I am about to fart"</span>,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">MINT_ExAc_2 =</span> </span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"I can always accurately feel when I am about to sneeze"</span>,</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">MINT_ExAc_3 =</span> </span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"I can always accurately feel when I am about to burp"</span>,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">MINT_RelA_4 =</span> </span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"I always feel in my body if I am relaxed"</span>,</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">MINT_RelA_5 =</span> </span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"I always know when I am relaxed"</span>,</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">MINT_RelA_6 =</span></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"My body is always in the same specific state when I am relaxed"</span>,</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">MINT_SexS_7 =</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">"During sex or masturbation, I often feel very strong sensations coming from my genital areas"</span>,</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">MINT_SexS_8 =</span></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">"My genital organs are very sensitive to pleasant stimulations"</span>,</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">MINT_SexS_9 =</span></span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">"When I am sexually aroused, I often notice specific sensations in my genital area (e.g., tingling, warmth, wetness, stiffness, pulsations)"</span>,</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">MINT_CaCo_10 =</span></span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Sometimes my breathing becomes erratic or shallow and I often don't know why"</span>,</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">MINT_CaCo_11 =</span></span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>    <span class="st">"I often feel like I can't get enough oxygen by breathing normally"</span>,</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">MINT_CaCo_12 =</span></span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Sometimes my heart starts racing and I often don't know why"</span>,</span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">MINT_Urin_13 =</span></span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>    <span class="st">"I sometimes feel like I need to urinate or defecate but when I go to the bathroom I produce less than I expected"</span>,</span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a>  <span class="at">MINT_Urin_14 =</span></span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a>    <span class="st">"I often feel the need to urinate even when my bladder is not full"</span>,</span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a>  <span class="at">MINT_Urin_15 =</span></span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Sometimes I am not sure whether I need to go to the toilet or not (to urinate or defecate)"</span>,</span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a>  <span class="at">MINT_Derm_16 =</span> </span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a>    <span class="st">"In general, my skin is very sensitive"</span>,</span>
<span id="cb7-34"><a href="#cb7-34" aria-hidden="true" tabindex="-1"></a>  <span class="at">MINT_Derm_17 =</span> </span>
<span id="cb7-35"><a href="#cb7-35" aria-hidden="true" tabindex="-1"></a>    <span class="st">"My skin is susceptible to itchy fabrics and materials"</span>,</span>
<span id="cb7-36"><a href="#cb7-36" aria-hidden="true" tabindex="-1"></a>  <span class="at">MINT_Derm_18 =</span></span>
<span id="cb7-37"><a href="#cb7-37" aria-hidden="true" tabindex="-1"></a>    <span class="st">"I can notice even very subtle stimulations to my skin (e.g., very light touches)"</span>,</span>
<span id="cb7-38"><a href="#cb7-38" aria-hidden="true" tabindex="-1"></a>  <span class="at">MINT_Sati_19 =</span></span>
<span id="cb7-39"><a href="#cb7-39" aria-hidden="true" tabindex="-1"></a>    <span class="st">"I don't always feel the need to eat until I am really hungry"</span>,</span>
<span id="cb7-40"><a href="#cb7-40" aria-hidden="true" tabindex="-1"></a>  <span class="at">MINT_Sati_20 =</span></span>
<span id="cb7-41"><a href="#cb7-41" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Sometimes I don't realise I was hungry until I ate something "</span>,</span>
<span id="cb7-42"><a href="#cb7-42" aria-hidden="true" tabindex="-1"></a>  <span class="at">MINT_Sati_21 =</span></span>
<span id="cb7-43"><a href="#cb7-43" aria-hidden="true" tabindex="-1"></a>    <span class="st">"I don't always feel the need to drink until I am really thirsty"</span>,</span>
<span id="cb7-44"><a href="#cb7-44" aria-hidden="true" tabindex="-1"></a>  <span class="at">MINT_Olfa_22 =</span> </span>
<span id="cb7-45"><a href="#cb7-45" aria-hidden="true" tabindex="-1"></a>    <span class="st">"I often check the smell of my armpits"</span>,</span>
<span id="cb7-46"><a href="#cb7-46" aria-hidden="true" tabindex="-1"></a>  <span class="at">MINT_Olfa_23 =</span> </span>
<span id="cb7-47"><a href="#cb7-47" aria-hidden="true" tabindex="-1"></a>    <span class="st">"I often check the smell of my own breath"</span>,</span>
<span id="cb7-48"><a href="#cb7-48" aria-hidden="true" tabindex="-1"></a>  <span class="at">MINT_Olfa_24 =</span> </span>
<span id="cb7-49"><a href="#cb7-49" aria-hidden="true" tabindex="-1"></a>    <span class="st">"I often check the smell of my farts"</span>,</span>
<span id="cb7-50"><a href="#cb7-50" aria-hidden="true" tabindex="-1"></a>  <span class="at">MINT_Resp_25 =</span> </span>
<span id="cb7-51"><a href="#cb7-51" aria-hidden="true" tabindex="-1"></a>    <span class="st">"In general, I am very sensitive to changes in my breathing"</span>,</span>
<span id="cb7-52"><a href="#cb7-52" aria-hidden="true" tabindex="-1"></a>  <span class="at">MINT_Resp_26 =</span> </span>
<span id="cb7-53"><a href="#cb7-53" aria-hidden="true" tabindex="-1"></a>    <span class="st">"I can notice even very subtle changes in my breathing"</span>,</span>
<span id="cb7-54"><a href="#cb7-54" aria-hidden="true" tabindex="-1"></a>  <span class="at">MINT_Resp_27 =</span></span>
<span id="cb7-55"><a href="#cb7-55" aria-hidden="true" tabindex="-1"></a>    <span class="st">"I am always very aware of how I am breathing, even when I am calm"</span>,</span>
<span id="cb7-56"><a href="#cb7-56" aria-hidden="true" tabindex="-1"></a>  <span class="at">MINT_Card_28 =</span> </span>
<span id="cb7-57"><a href="#cb7-57" aria-hidden="true" tabindex="-1"></a>    <span class="st">"In general, I am very sensitive to changes in my heart rate"</span>,</span>
<span id="cb7-58"><a href="#cb7-58" aria-hidden="true" tabindex="-1"></a>  <span class="at">MINT_Card_29 =</span> </span>
<span id="cb7-59"><a href="#cb7-59" aria-hidden="true" tabindex="-1"></a>    <span class="st">"I often notice changes in my heart rate"</span>,</span>
<span id="cb7-60"><a href="#cb7-60" aria-hidden="true" tabindex="-1"></a>  <span class="at">MINT_Card_30 =</span></span>
<span id="cb7-61"><a href="#cb7-61" aria-hidden="true" tabindex="-1"></a>    <span class="st">"I can notice even very subtle changes in the way my heart beats"</span>,</span>
<span id="cb7-62"><a href="#cb7-62" aria-hidden="true" tabindex="-1"></a>  <span class="at">MINT_Gast_31 =</span></span>
<span id="cb7-63"><a href="#cb7-63" aria-hidden="true" tabindex="-1"></a>    <span class="st">"I can notice even very subtle changes in what my stomach is doing"</span>,</span>
<span id="cb7-64"><a href="#cb7-64" aria-hidden="true" tabindex="-1"></a>  <span class="at">MINT_Gast_32 =</span> </span>
<span id="cb7-65"><a href="#cb7-65" aria-hidden="true" tabindex="-1"></a>    <span class="st">"In general, I am very sensitive to what my stomach is doing"</span>,</span>
<span id="cb7-66"><a href="#cb7-66" aria-hidden="true" tabindex="-1"></a>  <span class="at">MINT_Gast_33 =</span></span>
<span id="cb7-67"><a href="#cb7-67" aria-hidden="true" tabindex="-1"></a>    <span class="st">"I am always very aware of what my stomach is doing, even when I am calm"</span></span>
<span id="cb7-68"><a href="#cb7-68" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>cleanlabels <span class="ot">&lt;-</span> <span class="cf">function</span>(x, <span class="at">qname=</span><span class="cn">FALSE</span>) {</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  is_factor <span class="ot">&lt;-</span> <span class="cn">FALSE</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(<span class="fu">is.factor</span>(x)) {</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    is_factor <span class="ot">&lt;-</span> <span class="cn">TRUE</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    vec <span class="ot">&lt;-</span> x</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    x <span class="ot">&lt;-</span> <span class="fu">levels</span>(x)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  x <span class="ot">&lt;-</span> x <span class="sc">|&gt;</span> </span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">str_replace</span>(<span class="st">"MINT_"</span>, <span class="fu">ifelse</span>(qname, <span class="st">"MINT - "</span>, <span class="st">""</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">str_replace</span>(<span class="st">"_"</span>, <span class="st">" - "</span>) </span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(is_factor) {</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">levels</span>(vec) <span class="ot">&lt;-</span> x</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(vec)</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>  x</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
</section>
<section id="replicate-ega-from-interoceptionscale-study-2" class="level1">
<h1>3. Replicate EGA from InteroceptionScale Study 2</h1>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>ega <span class="ot">&lt;-</span> <span class="fu">bootEGA</span>(</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  mint_items,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">EGA.type =</span> <span class="st">"hierEGA"</span>,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">model =</span> <span class="st">"glasso"</span>,  <span class="co"># BGGM</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">algorithm =</span> <span class="st">"leiden"</span>,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># consensus.method = "lowest_tefi",</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">allow.singleton =</span> <span class="cn">TRUE</span>,</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">type=</span><span class="st">"resampling"</span>,</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">plot.itemStability=</span><span class="cn">FALSE</span>,</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">typicalStructure=</span><span class="cn">TRUE</span>,</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">plot.typicalGraph=</span><span class="cn">FALSE</span>,</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">iter=</span><span class="dv">500</span>,</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">seed=</span><span class="dv">3</span>, </span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">ncores =</span> <span class="dv">4</span>)</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(ega, <span class="at">file=</span><span class="st">"models/ega.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"models/ega.RData"</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>EGAnet<span class="sc">::</span><span class="fu">dimensionStability</span>(ega)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Ignoring unknown labels:
• fill : "Communities"
• linetype : "Communities"
• shape : "Communities"
Ignoring unknown labels:
• fill : "Communities"
• linetype : "Communities"
• shape : "Communities"</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2_analysis_emma_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>EGA Type: hierEGA 
Bootstrap Samples: 500 (Resampling)

Proportion Replicated in Dimensions:

       Urin_14 ExAc_3 Urin_13 ExAc_1 Sati_19 Sati_21 ExAc_2 SexS_7 SexS_9
Lower        1      1       1      1   1.000   1.000      1      1      1
Higher       1      1       1      1   0.998   0.998      1      1      1
       CaCo_11 SexS_8 CaCo_10 Urin_15 Sati_20 CaCo_12 RelA_5 Derm_16 RelA_6
Lower    1.000      1   1.000       1   1.000   1.000      1   1.000      1
Higher   0.998      1   0.998       1   0.998   0.998      1   0.622      1
       Resp_25 Gast_31 Card_30 Gast_32 Resp_26 Resp_27 Olfa_23 Derm_17 Olfa_24
Lower        1    1.00       1    1.00       1       1   1.000   1.000   1.000
Higher       1    0.98       1    0.98       1       1   0.722   0.622   0.722
       Gast_33 Card_28 RelA_4 Card_29 Derm_18 Olfa_22
Lower     1.00       1      1       1   1.000   1.000
Higher    0.98       1      1       1   0.622   0.722

----

Structural Consistency:

[1;m[4;mLower Order

[0m[0m 1  2  3  4  5  6  7  8  9 10 11 
 1  1  1  1  1  1  1  1  1  1  1 
[1;m[4;m

Higher Order

[0m[0m    1     2     3 
0.552 1.000 0.980 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>itemstability <span class="ot">&lt;-</span> EGAnet<span class="sc">::</span><span class="fu">itemStability</span>(ega, <span class="at">IS.plot=</span><span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Ignoring unknown labels:
• fill : "Communities"
• linetype : "Communities"
• shape : "Communities"
Ignoring unknown labels:
• fill : "Communities"
• linetype : "Communities"
• shape : "Communities"</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>p_stab <span class="ot">&lt;-</span> <span class="fu">plot</span>(itemstability)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>p_stab</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>EGAnet<span class="sc">::</span><span class="fu">genTEFI</span>(ega<span class="sc">$</span>EGA)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  VN.Entropy.Fit Level_1_VN Level_2_VN
1      -70.21302   -23.5941  -46.61892</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>ega<span class="sc">$</span>EGA</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1;m[4;mLower Order

[0m[0mModel: GLASSO (EBIC with gamma = 0.5)
Correlations: auto
Lambda: 0.0761570595617476 (n = 100, ratio = 0.1)

Number of nodes: 33
Number of edges: 188
Edge density: 0.356

Non-zero edge weights: 
     M    SD    Min   Max
 0.073 0.109 -0.080 0.494

----

Consensus Method: Most Common (1000 iterations)
Algorithm: Louvain
Order: Lower

Number of communities:  11

Urin_14  ExAc_3 Urin_13  ExAc_1 Sati_19 Sati_21  ExAc_2  SexS_7  SexS_9 CaCo_11 
      1       2       1       2       3       3       2       4       4       5 
 SexS_8 CaCo_10 Urin_15 Sati_20 CaCo_12  RelA_5 Derm_16  RelA_6 Resp_25 Gast_31 
      4       5       1       3       5       6       7       6       8       9 
Card_30 Gast_32 Resp_26 Resp_27 Olfa_23 Derm_17 Olfa_24 Gast_33 Card_28  RelA_4 
     10       9       8       8      11       7      11       9      10       6 
Card_29 Derm_18 Olfa_22 
     10       7      11 

----

Unidimensional Method: Louvain (Most Common for 1000 iterations)
Unidimensional: No

----

TEFI: -23.594

------------

[1;m[4;mHigher Order

[0m[0mModel: GLASSO (EBIC with gamma = 0.5)
Correlations: auto
Lambda: 0.0700503865947518 (n = 100, ratio = 0.1)

Number of nodes: 11
Number of edges: 37
Edge density: 0.673

Non-zero edge weights: 
     M    SD    Min   Max
 0.094 0.103 -0.158 0.473

----

Algorithm:  Leiden with Modularity

Number of communities:  3

01 02 03 04 05 06 07 08 09 10 11 
 1  2  1  2  1  2  1  3  3  3  1 

----

Unidimensional Method: Louvain (Most Common for 1000 iterations)
Unidimensional: No

----

TEFI: -46.619

----

Generalized TEFI: -70.213

----

Interpretation: Based on lower (-23.594) and higher (-46.619) TEFI, there is better fit for a bifactor structure than correlated lower order factor structure</code></pre>
</div>
</div>
<p>Lower-order dimensions are very stable. Higher-order dimensions are mostly stable but a few items show ambiguity (Derm 16, 17 &amp; 18, Olfa 22, 23 &amp; 24).</p>
<p>Deficit metacluster is less consistent (0.546) - less robust, possibly due to heterogeneous items</p>
<p>Network characteristics: Lower-order network - 33 nodes, 194 edges, edge density 0.367. Most edges are small (0.071 ± 0.108), range -0.088 to 0.48 → mostly weak to moderate partial correlations. Higher-order network - 11 nodes (representing lower-order communities), 36 edges, edge density 0.655 → more connected than lower-order network. Edge weights are slightly stronger on average (0.096 ± 0.103), some negative → stronger inter-community relationships, but some inverse relationships.</p>
<p>Total Entropy Fit Index: More negative TEFI = better fit of bifactor/hierarchical model. Results suggest a bifactor structure fits better than just correlated lower-order factors.</p>
</section>
<section id="clustering" class="level1">
<h1>4. Clustering</h1>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Scale data</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>mint_scaled <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">scale</span>(mint_lowerorder))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<section id="estimate-number-of-clusters" class="level2">
<h2 class="anchored" data-anchor-id="estimate-number-of-clusters">4.1. Estimate Number of Clusters</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>cluster_estimate <span class="ot">&lt;-</span> <span class="fu">n_clusters</span>(</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  mint_scaled,</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">package =</span> <span class="fu">c</span>(<span class="st">"all"</span>),</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">n_max =</span> <span class="dv">10</span>,</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: did not converge in 10 iterations
Warning: did not converge in 10 iterations
Warning: did not converge in 10 iterations
Warning: did not converge in 10 iterations
Warning: did not converge in 10 iterations
Warning: did not converge in 10 iterations
Warning: did not converge in 10 iterations
Warning: did not converge in 10 iterations
Warning: did not converge in 10 iterations
Warning: did not converge in 10 iterations</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `aes_string()` was deprecated in ggplot2 3.0.0.
ℹ Please use tidy evaluation idioms with `aes()`.
ℹ See also `vignette("ggplot2-in-packages")` for more information.
ℹ The deprecated feature was likely used in the factoextra package.
  Please report the issue at &lt;https://github.com/kassambara/factoextra/issues&gt;.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: did not converge in 10 iterations
Warning: did not converge in 10 iterations
Warning: did not converge in 10 iterations
Warning: did not converge in 10 iterations
Warning: did not converge in 10 iterations
Warning: did not converge in 10 iterations
Warning: did not converge in 10 iterations
Warning: did not converge in 10 iterations
Warning: did not converge in 10 iterations
Warning: did not converge in 10 iterations</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>cluster_estimate</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># Method Agreement Procedure:

The choice of 3 clusters is supported by 10 (34.48%) methods out of 29 (Hartigan, Scott, trcovw, Tracew, Friedman, Rubin, Ratkowsky, Ball, SDindex, Mixture (VVE)).</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cluster_estimate)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2_analysis_emma_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Method Agreement Procedure: The choice of 3 clusters is supported by 10 (34.48%) methods out of 29 (Hartigan, Scott, trcovw, Tracew, Friedman, Rubin, Ratkowsky, Ball, SDindex, Mixture (VVE)).</p>
</section>
<section id="kmeans" class="level2">
<h2 class="anchored" data-anchor-id="kmeans">4.2. Kmeans</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 3 clusters</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>rez_kmeans3 <span class="ot">&lt;-</span> <span class="fu">cluster_analysis</span>(mint_scaled, <span class="at">n =</span> <span class="dv">3</span>, <span class="at">method =</span> <span class="st">"kmeans"</span>)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>rez_kmeans3</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># Clustering Solution

The 3 clusters accounted for 25.87% of the total variance of the original data.

Cluster | n_Obs | Sum_Squares | MINT_SexS | MINT_ExAc | MINT_RelA | MINT_CaCo | MINT_Urin | MINT_Derm | MINT_Sati | MINT_Olfa | MINT_Card | MINT_Resp | MINT_Gast
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
1       |   556 |     4387.05 |     -0.17 |     -0.27 |     -0.42 |      0.87 |      0.67 |      0.33 |      0.46 |      0.16 |      0.41 |      0.28 |      0.18
2       |   624 |     5587.34 |     -0.24 |     -0.30 |     -0.25 |     -0.62 |     -0.40 |     -0.62 |     -0.26 |     -0.47 |     -0.85 |     -0.83 |     -0.71
3       |   509 |     3790.31 |      0.48 |      0.66 |      0.77 |     -0.19 |     -0.23 |      0.39 |     -0.18 |      0.40 |      0.60 |      0.71 |      0.67

# Indices of model performance

Sum_Squares_Total | Sum_Squares_Between | Sum_Squares_Within |    R2
--------------------------------------------------------------------
18568.000         |            4803.300 |          13764.700 | 0.259

# You can access the predicted clusters via `predict()`.</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(rez_kmeans3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2_analysis_emma_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(rez_kmeans3) <span class="co"># Get clusters</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   [1] 2 2 3 2 3 3 1 3 2 1 3 3 2 2 3 1 2 2 3 3 3 3 1 1 1 3 2 2 3 1 2 1 2 2 2 3 1
  [38] 3 3 1 1 1 1 3 2 1 3 2 2 2 1 3 2 2 3 1 1 2 1 3 2 2 1 3 1 2 2 1 2 3 2 1 1 1
  [75] 2 1 1 3 2 2 1 3 3 3 1 2 2 3 1 3 1 1 3 1 2 3 1 2 3 2 3 2 2 3 1 3 1 1 2 2 1
 [112] 3 2 3 3 1 3 2 1 1 1 3 1 2 3 1 1 1 3 1 1 1 3 1 2 3 3 2 1 2 3 1 2 3 3 2 3 1
 [149] 3 1 1 3 2 2 2 2 2 3 2 1 2 2 3 3 1 2 1 1 3 3 3 1 1 3 1 2 2 2 2 1 3 3 1 1 2
 [186] 3 3 1 1 2 3 1 2 3 3 3 2 3 1 1 2 1 2 2 1 1 3 3 1 2 3 2 2 2 1 1 2 2 3 1 2 1
 [223] 2 1 1 1 3 3 1 3 1 3 3 3 3 2 1 2 3 3 3 1 3 2 2 2 2 2 3 3 1 3 3 2 2 1 1 2 3
 [260] 2 3 1 3 1 2 3 2 1 1 1 2 3 1 2 3 1 1 3 3 2 3 3 1 2 1 1 2 1 3 3 3 2 2 3 2 2
 [297] 3 1 1 1 2 2 3 3 2 3 3 3 1 1 2 3 1 1 3 3 2 1 2 2 3 1 2 1 3 2 3 2 1 3 3 3 2
 [334] 1 3 1 3 2 3 1 3 1 2 1 3 3 2 3 1 3 2 3 3 2 1 3 2 3 2 1 3 3 3 3 1 1 2 1 2 3
 [371] 2 3 2 2 2 3 3 3 2 1 3 3 3 2 2 2 1 3 2 1 1 3 3 1 3 3 1 2 2 1 3 3 1 3 3 1 2
 [408] 1 1 3 1 1 1 2 3 2 1 3 1 2 3 1 3 2 2 3 2 3 2 2 2 1 2 1 3 3 3 1 1 1 2 1 1 2
 [445] 3 3 2 1 1 2 1 2 1 2 2 2 3 2 3 3 3 2 2 1 2 1 3 3 3 2 1 2 2 3 2 1 1 3 2 1 2
 [482] 1 1 2 3 3 2 2 1 2 2 2 2 1 2 2 2 1 1 1 2 3 3 1 3 1 2 3 1 2 2 1 3 1 1 2 1 2
 [519] 2 3 1 2 1 1 1 3 2 2 3 1 1 3 3 2 2 2 3 3 3 3 2 2 2 2 2 3 2 2 1 1 1 1 3 3 1
 [556] 3 2 1 2 3 1 1 2 1 1 2 1 1 1 1 1 3 1 3 2 3 1 1 1 2 2 2 3 2 3 1 3 3 2 2 2 3
 [593] 1 3 2 2 1 1 3 2 1 2 2 2 1 1 2 2 1 1 3 3 2 3 3 3 1 2 1 1 1 2 2 1 1 2 2 3 3
 [630] 3 2 2 3 1 1 1 1 1 1 1 2 1 3 2 3 3 1 3 1 1 1 2 1 3 2 2 3 3 3 1 3 3 3 2 2 3
 [667] 3 2 3 1 3 1 1 3 1 1 3 2 1 2 3 1 1 3 3 2 3 1 3 1 1 2 3 2 1 1 1 2 1 2 1 2 1
 [704] 2 3 1 1 1 3 3 2 1 3 3 2 3 3 2 1 1 2 1 1 2 1 1 1 3 1 2 2 3 3 2 1 1 2 1 2 1
 [741] 3 2 1 3 3 1 2 2 3 1 2 1 2 2 3 2 2 2 2 1 1 2 3 2 1 2 2 3 1 2 3 3 1 2 1 2 1
 [778] 3 1 2 3 2 2 2 2 1 1 3 3 1 3 1 3 2 2 3 1 1 1 2 3 2 3 2 3 1 2 1 1 3 1 3 2 1
 [815] 1 3 1 3 1 2 2 3 3 3 2 3 2 3 2 3 2 2 3 1 3 2 2 2 3 2 2 2 1 2 1 1 1 2 2 2 2
 [852] 1 2 2 2 3 2 1 3 3 1 1 2 1 3 3 2 1 3 2 3 2 1 2 1 1 3 1 1 2 3 1 2 1 2 2 2 2
 [889] 2 2 2 1 3 2 2 3 2 1 3 3 2 1 2 1 2 1 2 3 2 3 1 2 1 2 2 3 3 3 3 1 1 1 1 2 2
 [926] 2 1 3 2 2 1 1 1 2 3 3 2 3 3 1 2 3 1 1 2 2 2 2 1 2 2 1 3 3 3 1 1 2 1 2 1 2
 [963] 1 1 3 2 1 1 3 1 1 2 3 3 2 3 2 1 1 1 2 2 1 1 1 1 3 1 2 2 1 2 2 3 3 1 1 2 2
[1000] 2 2 1 1 2 3 2 2 3 2 1 1 3 3 1 2 2 3 1 1 1 2 1 3 2 3 2 1 1 3 1 3 3 3 3 2 2
[1037] 1 3 3 3 1 2 3 3 1 2 3 1 2 3 2 2 3 3 1 2 3 1 3 1 1 2 1 1 2 3 2 1 3 3 1 3 3
[1074] 1 3 1 2 3 2 1 1 2 3 2 1 1 3 1 1 1 1 3 1 2 2 1 2 2 2 1 1 3 3 1 1 2 3 1 2 1
[1111] 1 2 1 3 3 1 3 1 3 2 3 1 1 3 1 1 2 3 3 2 3 2 3 1 3 2 2 2 3 2 1 3 1 2 2 3 1
[1148] 2 3 2 2 1 1 2 1 3 2 1 3 1 1 3 1 3 3 1 3 2 3 3 3 2 1 2 1 2 3 3 2 3 3 1 2 2
[1185] 1 3 2 3 1 2 1 2 2 3 2 1 3 2 2 2 1 1 2 2 1 2 3 2 1 1 1 1 2 1 1 3 1 1 3 3 3
[1222] 2 2 1 1 3 1 2 1 3 3 2 1 1 3 1 1 2 3 3 2 1 1 2 1 1 1 1 2 2 3 3 2 1 2 1 1 2
[1259] 2 2 1 1 1 3 1 2 3 3 3 3 2 1 3 2 3 3 1 2 3 1 3 2 1 1 1 1 1 2 2 1 1 2 3 2 1
[1296] 3 1 2 1 2 1 2 1 3 2 2 2 3 2 2 2 2 2 1 2 1 2 1 3 3 3 2 2 3 3 3 2 1 2 3 2 1
[1333] 2 2 3 1 3 2 2 2 1 2 3 3 2 3 2 3 2 2 3 1 2 3 1 1 1 1 2 3 3 3 2 2 2 1 1 1 3
[1370] 3 2 2 1 2 2 2 2 1 3 2 2 2 2 1 2 2 3 3 3 2 2 1 3 2 3 1 3 1 3 1 1 1 2 2 3 2
[1407] 2 1 3 3 2 2 2 2 2 2 3 2 3 2 3 1 1 1 3 2 3 2 2 2 2 3 2 3 2 2 3 1 2 3 1 2 2
[1444] 2 2 2 2 3 3 2 1 1 2 2 2 3 2 2 2 3 1 1 2 2 2 2 1 1 1 2 3 2 1 2 2 2 2 1 2 3
[1481] 2 1 2 3 2 2 2 2 3 2 3 2 1 2 1 2 3 3 1 2 3 2 2 1 1 2 1 3 1 3 2 3 3 2 2 1 3
[1518] 3 3 3 2 3 1 1 1 2 2 1 2 2 2 2 3 2 2 2 2 2 3 3 2 2 1 1 3 3 2 1 2 2 3 2 2 2
[1555] 3 3 2 3 1 2 1 3 3 2 3 3 1 2 3 3 1 1 1 3 3 1 1 3 2 3 2 2 3 2 2 1 2 2 2 3 3
[1592] 3 2 3 2 1 1 2 1 3 1 2 1 2 2 2 2 1 2 3 2 2 1 1 1 3 2 3 2 2 2 2 2 3 3 1 2 3
[1629] 2 2 2 2 1 2 2 2 2 1 1 2 1 3 3 2 2 1 1 1 1 2 3 2 1 1 1 2 1 2 3 1 3 1 3 2 3
[1666] 2 1 1 1 3 2 3 2 1 3 2 3 2 1 2 1 3 2 1 1 2 2 1 1</code></pre>
</div>
</div>
<p>Cluster 2 (Low across most facets) - Globally low interoception Especially low on: Cardioception (-0.84) Respiroception (-0.82) Dermal Hypersensitivity (-0.58)</p>
<p>Cluster 3 - High awareness/relatively low confusion High on: Awareness facets (SexS, ExAc, RelA) and Visceroception (Card, Resp, Gast) But slightly low on deficit facets (CaCo, Urin)</p>
<p>Cluster 1 (Mixed pattern) - High confusion/dysregulated interoception High on Deficit facets (CaCo = +0.94, Urin = +0.71) Moderate/high elsewhere</p>
</section>
<section id="hierarchical-clustering" class="level2">
<h2 class="anchored" data-anchor-id="hierarchical-clustering">4.3. Hierarchical Clustering</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>rez_hclust <span class="ot">&lt;-</span> <span class="fu">cluster_analysis</span>(mint_scaled, <span class="at">n =</span> <span class="dv">3</span>, <span class="at">method =</span> <span class="st">"hclust"</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>rez_hclust</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># Clustering Solution

The 3 clusters accounted for 14.52% of the total variance of the original data.

Cluster | n_Obs | Sum_Squares | MINT_SexS | MINT_ExAc | MINT_RelA | MINT_CaCo | MINT_Urin | MINT_Derm | MINT_Sati | MINT_Olfa | MINT_Card | MINT_Resp | MINT_Gast
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
1       |  1137 |    10360.14 |      0.05 |     -0.05 |     -0.03 |     -0.23 |     -0.07 |     -0.17 |     -0.13 |     -0.17 |     -0.33 |     -0.30 |     -0.21
2       |   134 |     1498.73 |     -1.32 |     -0.86 |     -0.89 |      0.27 |     -0.04 |     -0.13 |      0.32 |     -0.22 |     -0.39 |     -0.54 |     -0.67
3       |   418 |     4012.17 |      0.27 |      0.40 |      0.36 |      0.54 |      0.21 |      0.51 |      0.26 |      0.52 |      1.03 |      1.00 |      0.78

# Indices of model performance

Sum_Squares_Total | Sum_Squares_Between | Sum_Squares_Within |    R2
--------------------------------------------------------------------
18568.000         |            2696.958 |          15871.042 | 0.145

# You can access the predicted clusters via `predict()`.</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(rez_hclust) <span class="sc">+</span> <span class="fu">theme_modern</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2_analysis_emma_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(rez_hclust)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   [1] 1 1 1 1 2 3 1 1 1 3 1 3 1 1 3 1 1 1 3 1 1 1 1 1 1 1 1 2 3 3 1 1 1 1 1 1 1
  [38] 1 1 3 1 1 1 3 1 1 1 1 1 1 3 3 1 1 1 1 1 2 1 1 1 1 3 3 1 1 1 1 1 3 1 3 2 1
  [75] 1 1 1 3 1 1 3 2 3 1 1 1 1 3 1 1 2 3 3 1 1 1 3 1 1 1 1 1 1 3 2 1 1 1 1 1 3
 [112] 1 1 3 3 1 1 1 1 2 1 3 1 1 3 1 3 1 1 2 1 1 1 1 1 1 1 1 1 1 1 3 1 1 1 2 3 3
 [149] 3 1 1 3 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 1 3 1 1 3 3 1 1 1 1 1 1 3 3 1 3 1
 [186] 1 3 1 1 1 3 3 2 1 1 3 1 3 2 3 1 3 1 2 1 1 1 1 3 1 3 1 1 1 3 1 1 3 3 1 1 3
 [223] 1 1 1 1 1 3 1 3 1 3 3 3 1 1 3 1 1 3 3 2 1 1 1 1 1 1 3 1 3 3 3 1 1 1 3 1 3
 [260] 1 1 3 1 3 1 3 2 3 1 1 1 3 1 1 3 3 1 3 3 1 3 1 1 1 1 1 1 1 1 1 1 1 1 3 1 1
 [297] 3 3 3 1 1 1 1 1 2 1 1 1 1 3 1 1 2 1 3 3 1 1 1 1 3 3 1 1 3 1 1 1 3 1 3 3 1
 [334] 1 3 3 1 1 3 1 1 1 1 1 3 3 1 3 1 3 1 3 1 1 1 1 1 3 1 1 1 3 1 1 1 1 1 3 1 1
 [371] 1 3 1 1 1 3 3 1 1 1 1 3 3 1 1 1 1 3 1 3 1 1 3 3 3 1 1 1 1 1 3 1 3 3 1 1 1
 [408] 1 1 1 1 3 3 1 1 2 3 1 1 1 3 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 3 1 1 3 1
 [445] 1 3 1 1 1 1 2 1 1 1 1 1 3 1 3 1 3 1 1 1 1 1 3 3 3 1 2 1 1 3 1 3 2 3 1 1 1
 [482] 3 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 3 1 3 3 1 3 1 1 1 1 1 1 1 1 2 3 1 1 1
 [519] 1 1 2 1 1 3 1 1 1 1 1 1 2 3 1 1 2 1 1 3 3 3 1 1 1 1 1 3 1 1 1 3 3 3 3 3 3
 [556] 3 1 2 1 3 3 2 2 3 1 1 3 3 1 1 3 3 2 3 1 3 1 1 3 1 1 1 3 1 1 3 3 1 1 1 1 1
 [593] 1 1 1 2 3 3 3 1 1 2 2 1 1 2 1 1 1 1 1 3 1 3 1 3 3 1 2 1 3 1 1 1 2 1 1 1 3
 [630] 3 2 1 3 3 1 2 2 3 1 1 1 1 3 1 1 1 1 1 1 2 1 1 1 3 1 1 1 3 3 3 3 1 1 1 1 3
 [667] 1 2 1 2 1 1 1 1 1 1 1 1 1 1 1 3 1 1 1 1 3 1 3 2 1 1 3 1 1 2 1 1 2 1 2 2 2
 [704] 1 1 1 1 1 1 1 1 3 1 1 2 1 1 1 3 3 1 3 1 1 1 2 1 1 1 1 1 3 1 2 1 1 1 1 1 3
 [741] 1 1 2 1 3 3 1 1 1 3 2 1 1 1 3 1 1 1 1 3 3 1 1 1 1 1 1 3 1 1 3 1 3 1 3 1 2
 [778] 1 1 1 1 1 1 1 2 3 1 3 3 3 3 3 3 1 1 1 2 1 1 1 1 1 3 1 3 1 1 1 3 1 1 1 1 1
 [815] 2 1 3 1 1 1 1 3 3 3 1 1 1 3 1 1 1 1 1 1 3 1 1 1 3 1 1 1 1 1 1 2 1 1 1 1 1
 [852] 3 1 1 1 3 1 2 2 1 1 3 1 3 1 3 1 1 3 2 3 1 1 1 1 1 1 3 1 1 3 1 1 1 1 1 1 1
 [889] 1 1 1 1 1 2 1 3 1 1 1 3 1 1 1 3 2 3 1 3 1 3 3 1 2 2 1 1 1 3 1 1 1 3 2 1 1
 [926] 1 3 3 1 1 3 1 3 1 1 1 1 1 3 3 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1
 [963] 2 2 1 1 1 3 1 2 2 1 3 3 1 3 1 1 2 1 1 1 2 3 3 1 1 3 1 1 1 1 1 3 3 1 1 1 1
[1000] 1 1 3 2 2 1 1 1 1 2 3 3 1 1 3 1 1 1 1 3 3 1 1 1 1 1 1 1 1 1 1 3 1 3 3 1 2
[1037] 3 3 3 3 1 1 1 1 1 1 1 3 1 3 1 1 1 3 1 1 3 1 1 1 2 2 1 3 1 3 1 1 3 1 1 1 3
[1074] 1 1 3 2 1 1 2 3 1 3 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 3 1 1 3 1 1 3 1 1
[1111] 3 1 3 1 1 3 3 2 1 1 1 3 1 3 1 3 1 3 1 1 1 1 1 1 1 1 1 1 1 1 1 3 1 1 1 3 1
[1148] 1 3 1 1 1 1 1 1 3 1 3 1 2 1 1 3 3 1 1 3 1 3 1 3 1 3 1 1 1 1 3 1 1 3 2 1 1
[1185] 1 1 1 1 3 1 2 1 1 1 1 3 3 1 1 2 2 1 1 1 3 1 1 1 3 2 3 2 1 2 1 1 1 3 3 3 3
[1222] 1 1 1 1 1 1 1 1 3 3 1 2 3 1 1 1 1 3 3 1 1 3 1 2 3 1 3 1 1 1 1 1 1 1 3 1 1
[1259] 1 1 3 1 1 3 2 1 3 3 1 1 1 1 3 1 3 3 1 1 3 1 1 1 3 1 1 1 1 1 1 1 1 1 3 1 3
[1296] 1 1 1 1 1 1 1 3 1 1 1 1 3 1 1 1 1 1 1 2 1 1 2 3 1 3 1 1 3 3 1 1 1 1 1 1 3
[1333] 1 1 1 1 3 1 1 1 3 1 1 3 1 1 1 3 2 1 1 3 1 1 1 3 3 3 1 3 3 1 1 1 1 1 3 1 1
[1370] 1 1 1 3 1 1 1 1 2 1 1 1 2 1 3 1 2 3 1 3 1 1 1 1 1 1 1 1 2 3 1 1 1 1 1 1 1
[1407] 1 2 3 3 1 1 1 1 1 1 3 1 3 1 3 1 1 2 3 1 3 1 1 2 1 3 1 1 1 1 3 2 1 3 2 1 2
[1444] 1 1 1 1 3 3 2 1 1 1 1 1 1 2 1 1 3 1 1 2 1 1 1 3 2 1 1 3 1 3 1 2 2 1 1 1 3
[1481] 1 1 1 1 1 1 1 1 3 1 3 1 1 1 3 1 3 3 1 2 3 1 1 1 3 2 1 3 1 1 1 1 1 1 1 1 3
[1518] 3 3 3 1 1 1 1 2 1 1 3 1 1 1 2 1 1 1 1 1 1 1 3 1 1 2 1 1 3 2 1 1 1 3 1 1 2
[1555] 3 1 2 1 1 1 1 1 3 1 3 1 3 1 1 1 3 3 1 1 1 1 3 3 1 3 1 1 1 1 1 3 1 1 1 3 1
[1592] 1 1 1 2 3 1 1 3 3 1 1 1 1 1 1 1 1 1 1 1 2 3 1 3 1 1 1 1 2 1 1 1 1 1 1 1 1
[1629] 1 1 1 2 1 1 2 1 1 3 3 2 2 1 3 2 2 1 3 3 1 1 1 1 1 1 2 1 3 1 1 3 1 1 1 1 1
[1666] 1 1 3 2 1 1 3 1 1 1 1 1 1 3 1 1 3 2 1 3 1 1 2 3</code></pre>
</div>
</div>
</section>
<section id="hierarchical-k-means" class="level2">
<h2 class="anchored" data-anchor-id="hierarchical-k-means">4.4. Hierarchical K-Means</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>rez_hkmeans <span class="ot">&lt;-</span> <span class="fu">cluster_analysis</span>(mint_scaled, <span class="at">n =</span> <span class="dv">3</span>, <span class="at">method =</span> <span class="st">"hkmeans"</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>rez_hkmeans</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># Clustering Solution

The 3 clusters accounted for 25.73% of the total variance of the original data.

Cluster | n_Obs | Sum_Squares | MINT_SexS | MINT_ExAc | MINT_RelA | MINT_CaCo | MINT_Urin | MINT_Derm | MINT_Sati | MINT_Olfa | MINT_Card | MINT_Resp | MINT_Gast
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
1       |   517 |     3742.61 |      0.43 |      0.62 |      0.71 |     -0.36 |     -0.40 |      0.30 |     -0.32 |      0.20 |      0.44 |      0.53 |      0.56
2       |   629 |     5642.66 |     -0.31 |     -0.38 |     -0.36 |     -0.53 |     -0.32 |     -0.61 |     -0.18 |     -0.46 |     -0.82 |     -0.84 |     -0.73
3       |   543 |     4405.01 |     -0.05 |     -0.14 |     -0.25 |      0.96 |      0.76 |      0.42 |      0.51 |      0.34 |      0.53 |      0.47 |      0.31

# Indices of model performance

Sum_Squares_Total | Sum_Squares_Between | Sum_Squares_Within |    R2
--------------------------------------------------------------------
18568.000         |            4777.720 |          13790.280 | 0.257

# You can access the predicted clusters via `predict()`.</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(rez_hkmeans) <span class="sc">+</span> <span class="fu">theme_modern</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2_analysis_emma_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="k-medoids-pam" class="level2">
<h2 class="anchored" data-anchor-id="k-medoids-pam">4.5. K-Medoids (PAM)</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>rez_pam <span class="ot">&lt;-</span> <span class="fu">cluster_analysis</span>(mint_scaled, <span class="at">n =</span> <span class="dv">3</span>, <span class="at">method =</span> <span class="st">"pam"</span>)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>rez_pam</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># Clustering Solution

The 3 clusters accounted for 24.38% of the total variance of the original data.

Cluster | n_Obs | Sum_Squares | MINT_SexS | MINT_ExAc | MINT_RelA | MINT_CaCo | MINT_Urin | MINT_Derm | MINT_Sati | MINT_Olfa | MINT_Card | MINT_Resp | MINT_Gast
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
1       |   715 |     6338.03 |     -0.15 |     -0.24 |     -0.16 |     -0.59 |     -0.47 |     -0.57 |     -0.36 |     -0.51 |     -0.63 |     -0.64 |     -0.62
2       |   387 |     2963.48 |      0.60 |      0.65 |      0.77 |     -0.07 |      0.02 |      0.56 |     -0.25 |      0.68 |      0.71 |      0.86 |      0.92
3       |   587 |     4740.04 |     -0.22 |     -0.14 |     -0.32 |      0.77 |      0.56 |      0.33 |      0.60 |      0.17 |      0.30 |      0.21 |      0.15

# Indices of model performance

Sum_Squares_Total | Sum_Squares_Between | Sum_Squares_Within |    R2
--------------------------------------------------------------------
18568.000         |            4526.456 |          14041.544 | 0.244

# You can access the predicted clusters via `predict()`.</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(rez_pam) <span class="sc">+</span> <span class="fu">theme_modern</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2_analysis_emma_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="dbscan" class="level2">
<h2 class="anchored" data-anchor-id="dbscan">4.6. DBSCAN</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>eps <span class="ot">&lt;-</span> <span class="fu">n_clusters_dbscan</span>(mint_scaled, <span class="at">min_size =</span> <span class="fl">0.1</span>)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>eps</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>The DBSCAN method, based on the total clusters sum of squares, suggests that the optimal eps = 6.26846370830458 (with min. cluster size set to 169), which corresponds to 1 clusters.</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(eps) <span class="co"># Find the 'elbow' of the curve: 4.25</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2_analysis_emma_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>rez_dbscan <span class="ot">&lt;-</span> <span class="fu">cluster_analysis</span>(mint_scaled, <span class="at">method =</span> <span class="st">"dbscan"</span>, <span class="at">dbscan_eps =</span> <span class="fl">4.25</span>)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>rez_dbscan</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># Clustering Solution

The 2 clusters accounted for 1.47% of the total variance of the original data.

Cluster | n_Obs | Sum_Squares | MINT_SexS | MINT_ExAc | MINT_RelA | MINT_CaCo | MINT_Urin | MINT_Derm | MINT_Sati | MINT_Olfa | MINT_Card | MINT_Resp | MINT_Gast
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
0       |    46 |     1263.46 |     -1.57 |     -0.73 |     -1.05 |      0.14 |     -0.33 |     -0.19 |     -0.13 |     -0.62 |     -0.42 |     -0.49 |     -0.85
1       |  1643 |    17030.73 |      0.04 |      0.02 |      0.03 | -3.94e-03 |  9.36e-03 |  5.36e-03 |  3.75e-03 |      0.02 |      0.01 |      0.01 |      0.02

# Indices of model performance

Sum_Squares_Total | Sum_Squares_Between | Sum_Squares_Within |    R2
--------------------------------------------------------------------
18568.000         |             273.809 |          17030.730 | 0.015

# You can access the predicted clusters via `predict()`.</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(rez_dbscan) <span class="sc">+</span> <span class="fu">theme_modern</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2_analysis_emma_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Suggests the existence of 1 cluster. The 2 clusters accounted for 1.47% of the total variance of the original data.</p>
</section>
<section id="k-medoids-with-estimation-of-number-of-clusters-pamk" class="level2">
<h2 class="anchored" data-anchor-id="k-medoids-with-estimation-of-number-of-clusters-pamk">4.7. K-Medoids with estimation of number of clusters (pamk)</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>rez_pamk <span class="ot">&lt;-</span> <span class="fu">cluster_analysis</span>(mint_scaled, <span class="at">method =</span> <span class="st">"pamk"</span>)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>rez_pamk</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># Clustering Solution

The 2 clusters accounted for 17.50% of the total variance of the original data.

Cluster | n_Obs | Sum_Squares | MINT_SexS | MINT_ExAc | MINT_RelA | MINT_CaCo | MINT_Urin | MINT_Derm | MINT_Sati | MINT_Olfa | MINT_Card | MINT_Resp | MINT_Gast
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
1       |   742 |     6933.84 |     -0.25 |     -0.24 |     -0.12 |     -0.57 |     -0.43 |     -0.57 |     -0.18 |     -0.54 |     -0.61 |     -0.65 |     -0.61
2       |   947 |     8383.93 |      0.19 |      0.19 |      0.09 |      0.45 |      0.34 |      0.44 |      0.14 |      0.42 |      0.48 |      0.51 |      0.48

# Indices of model performance

Sum_Squares_Total | Sum_Squares_Between | Sum_Squares_Within |    R2
--------------------------------------------------------------------
18568.000         |            3250.235 |          15317.765 | 0.175

# You can access the predicted clusters via `predict()`.</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(rez_pamk) <span class="sc">+</span> <span class="fu">theme_modern</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2_analysis_emma_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The 2 clusters accounted for 17.50% of the total variance of the original data.</p>
</section>
<section id="mixture" class="level2">
<h2 class="anchored" data-anchor-id="mixture">4.8. Mixture</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>rez_mixture <span class="ot">&lt;-</span> <span class="fu">cluster_analysis</span>(mint_scaled, <span class="at">method =</span> <span class="st">"mixture"</span>)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>rez_mixture</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># Clustering Solution

The 4 clusters accounted for 13.43% of the total variance of the original data.

Cluster | n_Obs | Sum_Squares | MINT_SexS | MINT_ExAc | MINT_RelA | MINT_CaCo | MINT_Urin | MINT_Derm | MINT_Sati | MINT_Olfa | MINT_Card | MINT_Resp | MINT_Gast
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
1       |   586 |     5530.25 |      0.56 |      0.58 |      0.27 | -5.66e-03 |      0.07 |      0.03 |     -0.03 |      0.07 |     -0.19 |     -0.18 |     -0.13
2       |   250 |     3562.02 |     -0.71 |     -0.51 |     -0.55 |      0.06 |     -0.01 |  7.38e-03 |      0.04 |     -0.26 |     -0.01 |     -0.28 |     -0.18
3       |   361 |     3334.01 |     -0.83 |     -0.75 |     -0.31 |      0.02 |     -0.23 |     -0.64 |     -0.09 |     -0.40 |     -0.44 |     -0.39 |     -0.50
4       |   492 |     3647.68 |      0.31 |      0.12 |      0.19 |     -0.04 |      0.10 |      0.43 |      0.08 |      0.34 |      0.56 |      0.65 |      0.61

# Indices of model performance

Sum_Squares_Total | Sum_Squares_Between | Sum_Squares_Within |    R2
--------------------------------------------------------------------
18568.000         |            2494.044 |          16073.956 | 0.134

# You can access the predicted clusters via `predict()`.</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(rez_mixture) <span class="sc">+</span> <span class="fu">theme_modern</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2_analysis_emma_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The 4 clusters accounted for 13.43% of the total variance of the original data.</p>
</section>
</section>
<section id="metaclustering" class="level1">
<h1>5. Metaclustering</h1>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>list_of_results <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  rez_kmeans3, rez_hclust, rez_hkmeans, rez_pam, rez_pamk, rez_mixture, rez_dbscan</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>probability_matrix <span class="ot">&lt;-</span> <span class="fu">cluster_meta</span>(list_of_results)</span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the matrix as a reordered heatmap</span></span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a>heatmap <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">heatmap</span>(probability_matrix,</span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">scale =</span> <span class="st">"none"</span>,</span>
<span id="cb55-10"><a href="#cb55-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> grDevices<span class="sc">::</span><span class="fu">hcl.colors</span>(<span class="dv">256</span>, <span class="at">palette =</span> <span class="st">"inferno"</span>)</span>
<span id="cb55-11"><a href="#cb55-11" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2_analysis_emma_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>heatmap</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>$rowInd
   [1] 1224  222 1423 1239  681  214  308  965 1625 1665  174  197 1658 1523
  [15]  921  995 1510 1290 1279 1070 1178 1648 1622 1341  404  589  723  843
  [29] 1555 1370 1199 1142  999  753  608  288  549 1469 1165  811  967  747
  [43] 1487  690 1227 1385 1585  832 1544 1219  629  987 1000 1159  975 1040
  [57] 1213  905  720  292  490 1020 1599 1506 1169  994  991  719  282  572
  [71]  809 1472 1415  867  265  471 1411  855  369  346  250  263  860 1589
  [85]  528 1044 1309 1455 1681 1600 1557 1399 1303 1264 1096 1023  774  755
  [99]  721  438  328  101  183  583 1573 1463 1275  320  813  773  748  601
 [113]  374   41  145 1546 1526 1154 1019 1005  496  180  347  817 1293 1201
 [127]  963  335  769 1666 1356  758  515  536 1683   53  911 1621 1443 1228
 [141]  468 1133 1182  368  914 1668 1657 1623 1427 1364 1301 1254 1146 1115
 [155] 1086 1004  531  121  225 1677 1519 1400 1334 1312 1298 1294 1285 1280
 [169] 1230 1177 1072 1006  981  980  941  791  678  554  510  295  235  120
 [183]   39   99  856  888 1323 1640 1403 1194 1120  839  660  205  655  908
 [197] 1663 1635 1595 1566 1495 1386 1384 1362 1349 1331 1326 1304 1272 1267
 [211] 1260 1253 1249 1232 1203 1161 1100 1033 1016  974  957  857  837  833
 [225]  787  778  771  736  728  725  691  684  677  673  647  641  599  502
 [239]  439  420  408  360  348  321  283  279  218  213  209  168  115   98
 [253]    4   17 1662  136 1053 1632 1537  240  184  143   95   78    7   58
 [267] 1041 1631 1502 1259  547  543  187  313 1529 1346 1246 1017  859  836
 [281]  131  627  947  785  727   45  312 1087  913  711  597  480   50  425
 [295] 1608 1088  939  628  686  654 1497 1486 1274 1059  956  260  227   55
 [309]   70 1155 1127 1094 1022  988  893  820  796  776  613  375  341  304
 [323]  247  233  215  190  158  133   46   49 1319   40  378 1511 1343 1316
 [337]   79  211  920 1533 1689 1686 1676 1672 1656 1655 1644 1611 1603 1588
 [351] 1587 1581 1577 1572 1536 1535 1528 1505 1500 1493 1480 1478 1476 1473
 [365] 1467 1466 1446 1444 1442 1436 1430 1416 1410 1406 1398 1394 1389 1379
 [379] 1373 1339 1317 1315 1305 1283 1266 1265 1263 1261 1243 1240 1238 1225
 [393] 1217 1202 1200 1189 1174 1168 1156 1149 1147 1109 1108 1101 1095 1090
 [407] 1082 1046 1035 1025 1010  992  990  969  960  953  943  937  936  928
 [421]  906  895  870  863  858  854  848  841  827  807  805  804  801  800
 [435]  799  783  756  749  742  739  732  730  724  718  709  700  683  675
 [449]  666  664  644  634  623  611  595  593  592  578  563  553  550  542
 [463]  540  533  522  518  514  506  503  491  487  486  482  477  467  462
 [477]  458  452  441  435  431  416  402  401  398  392  377  363  352  327
 [491]  325  307  296  284  277  264  261  248  246  243  237  232  226  220
 [505]  216  207  204  200  196  188  175  164  161  156  148  111  109  106
 [519]   92   85   63   60   54   10   19 1347 1333 1311 1236 1193 1180 1172
 [533] 1064  996  886  861  840  766  764  760  701  697  692  674  638  581
 [547]  558  545  507  498  495  361  267   81  257 1688 1659 1642 1636 1628
 [561] 1550 1489 1452 1445 1435 1397 1376 1371 1357 1276 1257 1235 1234 1209
 [575] 1198 1143 1083 1038 1026  998  979  926  910  890  877  865  853  850
 [589]  849  818  816  795  761  745  689  669  625  591  584  511  497  437
 [603]  412  396  383  350  326  300  287  275  262  259  254  236  203  194
 [617]  176  153  108  103  102   88   86   84   73   34   67 1673 1645 1637
 [631] 1629 1624 1619 1615 1610 1604 1592 1590 1580 1552 1547 1539 1534 1531
 [645] 1524 1514 1513 1512 1477 1454 1432 1425 1419 1395 1388 1367 1352 1336
 [659] 1321 1292 1291 1270 1220 1218 1215 1211 1206 1197 1195 1183 1179 1171
 [673] 1163 1162 1148 1145 1131 1124 1110 1106 1099 1077 1068 1067 1066 1063
 [687] 1058 1049 1034 1012  986  972  966  959  951  948  942  934  933  932
 [701]  931  924  923  916  907  896  883  869  852  846  842  835  823  810
 [715]  803  802  793  789  781  775  765  744  743  740  715  713  708  698
 [729]  648  645  639  606  596  570  560  552  546  539  516  500  492  484
 [743]  449  446  440  432  430  424  419  390  385  384  381  380  379  373
 [757]  367  359  357  356  351  345  343  340  337  331  319  318  316  315
 [771]  314  310  309  305  299  286  278  276  274  272  270  255  251  245
 [785]  244  231  224  198  179  169  163  160  159  155  154  152  149  141
 [799]  140  138  137  130  126  122  105   97   83   71   69   68   61   59
 [813]   56   38   32   26   24   14    3   12  303 1061  562 1509 1441 1185
 [827]  193  100  139 1679 1606 1591 1578 1554 1553 1532 1521 1482 1353 1337
 [841] 1329 1255 1153 1102 1079 1075 1042  977  976  973  946  927  894  878
 [855]  874  872  825  737  735  703  682  667  631  618  551  525  504  455
 [869]  388  234  206  202  177  157  134  128  116   72   66   13   48 1584
 [883] 1561 1483  752  561  665 1687 1670 1669 1664 1654 1652 1549 1527 1504
 [897] 1496 1440 1429 1401 1383 1363 1327 1320 1288 1205 1204 1157 1105 1062
 [911] 1045 1028 1021 1013  912  909  889  754  658  598  576  575  571  513
 [925]  474  464  421  409  394  370  364  344  336  297  293  285  256  178
 [939]  151  132  107   96   29   74  579 1439 1626 1498 1475 1449 1431 1418
 [953] 1344 1328 1287 1208 1116 1092 1060  541  459  411  397  365  353  135
 [967]  219 1187 1520 1492 1471 1391 1380 1358 1345 1340 1286 1244 1231  997
 [981]  901  897  819  651  614  460  451  342  338  199   47  127  172 1308
 [995] 1646 1597 1565 1458 1438 1412 1409 1369 1365 1355 1342 1338 1229 1223
[1009] 1221 1114 1107 1103 1091 1076 1047  935  922  919  887  868  794  782
[1023]  607  566  544  512  493  426  423  417  414  329  271  230  192  170
[1037]   90  150 1543 1222  762 1158 1684 1678 1675 1671 1661 1638 1620 1612
[1051] 1607 1602 1586 1576 1575 1568 1541 1538 1508 1503 1499 1494 1479 1462
[1065] 1460 1457 1456 1450 1437 1424 1396 1393 1375 1374 1351 1332 1318 1314
[1079] 1313 1307 1302 1297 1295 1289 1269 1233 1216 1152 1151 1144 1137 1136
[1093] 1134 1130 1118 1057 1036 1032 1031 1024 1003 1001  958  945  902  899
[1107]  885  866  862  851  834  824  821  790  780  751  717  716  714  696
[1121]  659  656  652  650  640  636  633  624  617  588  573  548  534  526
[1135]  519  509  470  469  450  415  382  371  366  330  291  281  280  273
[1149]  269  258  253  242  241  210  201  182  173  171  144  125  112  110
[1163]    8   18 1210 1322  387 1122  726  445   21  372 1132  165  831 1150
[1177]  508 1685 1188 1078  772  189  301 1516 1359 1074 1069  621   43  521
[1191] 1071  530  499  147  457 1650 1639 1618 1609 1598 1593 1579 1548 1488
[1205] 1468 1422 1414 1296 1251 1247 1175 1166 1008  971  968  940  917  873
[1219]  838  786  759  702  688  679  609  577  564  532  527  523  481  479
[1233]  444  442  395  358  334  323  306  217  185  119  113   94   52   42
[1247]   51 1491 1054  476  610 1627 1522 1517 1481 1453 1433 1354 1300 1273
[1261] 1139 1123 1093 1029  970  950  930  828  706  695  657  653  582  574
[1275]  517  501  485  472  456  447  422  162   77   22    5   11 1570 1560
[1289] 1448 1176 1065  989  707  252   35  249 1680 1660 1490 1428 1426 1368
[1303] 1361 1250 1212 1138 1126 1056  978  826  757  705  680  676  671  626
[1317]  585  494  429  407  332   30  195 1617 1377 1128 1117 1084  964  875
[1331]  844  777  767  741  687  489  478    2  266 1563 1542 1392 1278 1277
[1345] 1214 1191 1190 1140 1135 1129 1119 1111 1104 1073 1052 1030  944  929
[1359]  915  904  900  898  881  812  784  779  768  763  750  722  670  642
[1373]  568  434  349  333  317  223  123  118  104   91   75    1   33 1039
[1387] 1421  535 1098 1614 1574 1567 1515 1366 1335 1167 1085  770  734  616
[1401]  565  453  362  294  191  146   76   36    9   16 1647 1601 1464 1417
[1415] 1350 1192 1113 1089 1037 1014  982  954  892  879  871  808  806  731
[1429]  668  662  604  488  463  454  436  400  389  239  208  117   89   28
[1443]   57 1653 1633 1605 1583 1564 1562 1559 1556 1530 1518 1459 1405 1404
[1457] 1390 1330 1325 1310 1299 1282 1248 1237 1226 1207 1196 1184 1141 1125
[1471] 1097 1080 1055 1048 1043 1018 1011  984  955  952  938  925  891  884
[1485]  882  876  845  822  815  814  788  746  733  729  710  699  693  672
[1499]  622  619  605  602  594  586  580  567  556  538  537  529  473  466
[1513]  465  443  428  399  393  354  322  298  228  221  186  181  166  142
[1527]  124  114   23   37 1641 1571  993 1306   65 1002 1262   82  289 1674
[1541] 1651 1643 1387 1382 1378 1009  985  962  880  646  620  569  555  483
[1555]  311  302   25   80 1634 1616 1594 1501 1408 1242 1015  798  797  643
[1569]  557  520  461  418  406  386  376  339   20  212 1485 1434 1372 1258
[1583] 1170 1164 1050  829  649   31  238 1682 1630 1545 1451 1447 1360 1245
[1597] 1112 1081 1027  949  918  864  830  661  635  615  612  603  587  559
[1611]  391  355   15   64 1667 1649 1613 1596 1582 1569 1558 1551 1540 1525
[1625] 1507 1484 1474 1470 1465 1461 1420 1413 1407 1402 1381 1348 1324 1284
[1639] 1281 1271 1268 1256 1252 1241 1186 1181 1173 1160 1121 1051 1007  983
[1653]  961  903  847  792  738  712  704  694  685  663  637  632  630  600
[1667]  590  524  505  475  448  433  427  413  410  405  403  324  290  268
[1681]  229  167  129   93   87   62   44    6   27

$colInd
   [1]  466 1468 1476 1382 1009  267  451  221  525  723  879  203  943  463
  [15] 1000  305  105  146  858 1061  471  703  690  715  531  650 1398 1200
  [29]  970  477  785  670   91  184 1408 1118  971  699  521  696  881 1425
  [43] 1219  823  218  275 1440 1427 1344 1321  279  835  830 1162  101  646
  [57]  235  381 1589 1507 1362 1252  969  935  916  667  594  426  387  291
  [71]  133    9   90  117 1107 1370  877  227  415 1649 1545 1316 1089  917
  [85]  942 1510 1343 1194  685  671  536  144  164  873 1355  921  727  397
  [99]  489 1175 1154  932   24  334 1637    7  779 1222  557  462   69  247
 [113] 1322  508  776 1569 1465 1159  686  604  575  544  436  389  326  263
 [127]   67   22   33 1651 1591 1570 1455 1395 1180 1136 1012  899  749  710
 [141]  709  684  618  513  460  410  405  396  392  378  356  290   13  171
 [155]  834  367  802 1485 1035 1030  851  570  496   50  287  782 1686 1673
 [169] 1592 1575 1522 1481 1477 1472 1411 1407 1369 1342 1330 1282 1270 1251
 [183] 1188 1091 1049 1043 1017 1013 1006  999  965  962  954  919  912  903
 [197]  857  853  833  733  716  674  657  590  529  487  458  441  437  430
 [211]  423  418  386  364  359  341  328  306  304  195  124   95   27   55
 [225] 1554   28  637 1683 1632 1612 1595 1547 1506 1450   58  153   59  649
 [239] 1503 1377 1147 1143  188  431 1559 1063  854  831  673  444  161  344
 [253] 1645 1378  963  743  905 1640 1265 1210 1093  979  603  777   82 1062
 [267] 1004  602  751 1036 1635 1620 1463 1430  734  631  416  193  204 1644
 [281] 1641 1557 1532 1500 1475 1457 1443 1386 1349 1315 1077  914  894  870
 [295]  797  702  668  596  535  563 1650  371 1312 1611 1479  374  179  347
 [309]  157  770 1680 1671 1636 1630 1627 1605 1598 1584 1581 1579 1542 1534
 [323] 1529 1526 1515 1502 1494 1490 1486 1483 1474 1470 1464 1458 1453 1447
 [337] 1444 1442 1429 1426 1413 1406 1394 1383 1365 1363 1338 1327 1313 1298
 [351] 1292 1289 1288 1274 1259 1255 1249 1238 1232 1228 1223 1213 1208 1204
 [365] 1203 1199 1187 1184 1176 1172 1168 1157 1150 1148 1140 1137 1127 1112
 [379] 1098 1097 1095 1079 1067 1056 1046 1026 1024 1015 1007  990  981  972
 [393]  966  960  958  951  948  941  934  907  891  890  889  886  885  883
 [407]  863  849  842  836  832  827  820  795  784  762  754  753  747  737
 [421]  730  721  700  698  680  665  655  644  608  600  595  589  582  581
 [435]  543  541  534  522  516  501  490  488  473  465  452  450  447  429
 [449]  427  425  424  407  385  375  373  351  317  311  301  296  292  284
 [463]  280  274  260  254  248  246  244  224  223  217  214  212  210  197
 [477]  190  185  162  155  154  118  113  109  103  102   87   79   46   35
 [491]   34   18   14    1    4 1609 1433 1423 1329 1195 1192 1183 1145 1132
 [505] 1109 1052 1016  998  993  989  930  926  924  850  829  804  694  626
 [519]  518  510  497  454  379  343  357 1656 1623 1617 1606 1604 1602 1588
 [533] 1587 1582 1537 1514 1496 1487 1454 1436 1431 1428 1415 1403 1390 1364
 [547] 1340 1307 1294 1278 1253 1193 1179 1106 1099 1065 1021 1001  945  929
 [561]  895  874  872  841  840  837  825  813  800  780  764  711  692  664
 [575]  652  607  547  492  481  456  455  433  414  333  319  314  293  255
 [589]  245  238  201  140   62   54   48    2   31 1687 1678 1676 1666 1664
 [603] 1658 1652 1634 1631 1629 1622 1621 1619 1607 1593 1585 1568 1564 1560
 [617] 1553 1552 1550 1549 1541 1538 1536 1535 1531 1530 1527 1521 1511 1492
 [631] 1466 1459 1446 1445 1439 1435 1420 1418 1416 1414 1412 1404 1391 1385
 [645] 1381 1380 1376 1375 1374 1372 1371 1359 1353 1350 1347 1345 1339 1334
 [659] 1333 1331 1323 1317 1311 1310 1309 1306 1305 1300 1271 1266 1260 1258
 [673] 1250 1244 1241 1206 1198 1190 1174 1151 1144 1138 1130 1120 1094 1084
 [687] 1051 1045 1042  992  982  977  975  950  947  946  925  915  909  901
 [701]  897  888  887  880  867  855  848  844  838  821  807  794  783  774
 [715]  767  766  759  758  757  756  748  742  739  731  724  718  704  678
 [729]  656  641  632  627  624  623  622  613  591  584  580  566  559  545
 [743]  542  528  527  519  511  507  495  493  484  479  475  472  470  420
 [757]  399  398  369  354  338  323  302  295  271  265  258  236  213  178
 [771]  177  176  166  159  156  151  143  138  110  100   98   86   80   75
 [785]   71   66   61   53   17   45 1387  629 1128 1590 1551 1497  505  181
 [799]  249 1659 1452 1041  861  640  526  520  432  318  205  256 1675 1626
 [813] 1335 1299 1131 1103 1087 1078 1075 1055 1029  860  826  772  741  663
 [827]  609  578  445  330  243  239  145    8   60 1677 1642 1624 1618 1574
 [841] 1562 1556 1533 1513 1488 1484 1456 1302 1235 1186 1165 1139 1072 1059
 [855] 1023 1008  987  955  953  865  818  816  812  796  763  744  717  714
 [869]  713  648  615  611  588  537  435  361  353  337  208  169  158  137
 [883]  136  112   99   11   84 1665 1610 1388 1379 1207 1135 1121 1070 1044
 [897]  810  728  705  681  312  308  303   47   16   39 1670 1478 1351 1314
 [911] 1304 1284 1272 1229 1170 1133 1047  893  892  675  448  282  189   96
 [925]   56   74 1129 1025  938  207  106  129 1661 1616 1594 1583 1558 1539
 [939] 1512 1434 1405 1397 1393 1354 1346 1326 1320 1296 1281 1269 1226 1216
 [953] 1177 1119 1115 1114 1092 1032  936  801  781  778  677  669  662  645
 [967]  628  585  533  486  485  402  370  363  327  307  289  261  250  194
 [981]  186  163  141   38   36   26   21    3   20 1111  251 1555 1471 1337
 [995] 1325 1293 1279 1231 1149  630  598  574  482  403  362  346  272  259
[1009]  241  215   64  192  503 1643 1563 1491 1352 1348 1239 1230 1076 1039
[1023]  871  793  789  693  459  446  404  350  345  332  310  299  219  170
[1037]  198 1518  382 1600 1540 1520 1498 1460 1419 1361 1276 1273 1267 1264
[1051] 1197 1178 1146 1124 1083  908  896  822  803  771  768  755  643  614
[1065]  599  587  583  576  469  467  461  352  348  335  325  321  281  278
[1079]  252  232  125   44   93  147  928  468  532 1682 1672 1580 1578 1565
[1093] 1546 1519 1517 1508 1489 1480 1449 1448 1437 1432 1421 1417 1410 1409
[1107] 1399 1360 1324 1319 1308 1275 1240 1221 1220 1181 1171 1164 1156 1142
[1121] 1117 1102 1073 1066 1057 1054 1050 1040 1038 1034 1031  994  976  974
[1135]  973  939  910  900  869  866  856  839  828  824  805  791  788  745
[1149]  732  689  687  666  659  658  654  633  572  560  556  554  553  546
[1163]  539  538  474  457  421  401  395  393  388  383  377  376  372  358
[1177]  339  316  315  297  294  266  253  240  234  233  230  228  211  196
[1191]  191  187  182  152  149  122  115  114  104   88   83   78   70   52
[1205]   29   19   15    6   12  725   25   65 1493 1516  769  695   32  167
[1219]  620  512  411  180  400 1286 1101  349   42   68  847  967 1402 1141
[1233] 1082  937  691  548  491  135  320  651 1155  269  592  697  384   49
[1247]  119  688 1625 1608  428 1401 1684 1663 1646 1628 1603 1597 1561 1523
[1261] 1461 1422 1400 1366 1287 1285 1280 1277 1263 1257 1242 1215 1185 1166
[1275] 1100 1090 1060 1058 1053 1027 1005  996  986  978  952  898  843  787
[1289]  729  707  683  639  569  530  517  509  504  449  438  434  422  419
[1303]  409  406  366  342  309  288  283  277  270  229  225  220  216  206
[1317]  183  165  150  139  132  121  108   94   77   23   41 1681 1674 1654
[1331] 1614 1544 1499 1396 1328 1237 1125 1074  956  920  605  523  355  324
[1345]  175  123   76  116 1662 1633 1601 1573 1482 1451 1301 1290 1254 1236
[1359] 1227 1202 1086 1028 1022  959  884  882  819  811  798  736  708  676
[1373]  653  601  577  498  340  273  226   43   89 1667 1653 1576 1566 1548
[1387] 1524 1509 1504 1469 1462 1392 1368 1336 1297 1291 1262 1247 1225 1224
[1401] 1217 1161 1153 1152 1134 1123 1110 1104 1096 1088 1085 1071 1068 1018
[1415]  997  991  980  961  957  944  902  876  875  868  845  814  808  806
[1429]  799  765  752  738  735  706  679  672  647  642  635  610  593  565
[1443]  549  506  494  483  464  453  442  408  391  380  365  360  300  286
[1457]  285  231  172  160  134  131  128  126  107   85   37   57  480 1303
[1471]  368  568 1669 1318  964 1245 1525  558  859  540    5 1182 1501 1389
[1485]  918  502  612 1647 1169 1069  621  616  174  331 1543 1233 1191  619
[1499] 1160 1648 1639 1638 1596 1577 1571 1505 1473 1384 1367 1356 1332 1295
[1513] 1248 1246 1211 1209 1167 1163 1158 1126 1113 1081 1011 1002  988  931
[1527]  904  852  817  773  750  722  719  682  524  515  443  439  394  276
[1541]  268  222  202  142  111   97   92   81   72   40   51 1214 1080  199
[1555]  636 1685 1679 1668 1613 1528 1268 1243 1234 1218 1205 1189 1173 1116
[1569] 1108 1037 1033  995  984  862  760  740  720  661  597  567  551  417
[1583]  390  336  257  237  209  173   63  168 1655 1441 1438  983  701  625
[1597]  514  242  120  130 1660 1495 1358 1283 1261 1196 1105 1064 1019 1014
[1611] 1010  985  933  864  712  634  564  552  478  440  329  322  264  262
[1625]  200   10   30 1688 1424 1212 1201 1003  949  923  913  846  815  726
[1639]  606  573  562   73  313 1689 1657 1615 1599 1586 1572 1567 1467 1373
[1653] 1357 1341 1256 1122 1048 1020  968  940  927  922  911  906  878  809
[1667]  792  790  786  775  761  746  660  638  617  586  579  571  561  555
[1681]  550  500  499  476  413  412  298  127  148

$Rowv
NULL

$Colv
NULL</code></pre>
</div>
</div>
</section>
<section id="extract-participants-from-clusters" class="level1">
<h1>6. Extract participants from clusters</h1>
<p>K-Medoids (PAM) clustering was chosen as the final clustering solution due to its similarity to the meta-clustering solution and its cluster stability.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>cluster_assignment <span class="ot">&lt;-</span> <span class="fu">predict</span>(rez_pam)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>mega_df <span class="ot">&lt;-</span> mega_df <span class="sc">|&gt;</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Clusters =</span> <span class="fu">factor</span>(</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>      cluster_assignment,</span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>),</span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a>      <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Cluster 1"</span>, <span class="st">"Cluster 2"</span>, <span class="st">"Cluster 3"</span>)</span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="analysis" class="level1">
<h1>7. Analysis</h1>
<section id="age" class="level2">
<h2 class="anchored" data-anchor-id="age">7.1. Age</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Effect size: small = .01, medium = .06, large = .14 </span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>aov_age <span class="ot">&lt;-</span> <span class="fu">aov</span>(Age <span class="sc">~</span> Clusters, <span class="at">data =</span> mega_df)</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(aov_age)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>              Df Sum Sq Mean Sq F value   Pr(&gt;F)    
Clusters       2  11256    5628   30.55 9.26e-14 ***
Residuals   1686 310580     184                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">eta_squared</span>(aov_age)  <span class="co"># effect size</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>For one-way between subjects designs, partial eta squared is equivalent
  to eta squared. Returning eta squared.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># Effect Size for ANOVA

Parameter | Eta2 |       95% CI
-------------------------------
Clusters  | 0.03 | [0.02, 1.00]

- One-sided CIs: upper bound fixed at [1.00].</code></pre>
</div>
</div>
<p>F(2, 1686) = 30.55, p &lt; .001 Age explains 3% of the variance in cluster membership - small effect size</p>
</section>
<section id="depression-anxiety-phq-4" class="level2">
<h2 class="anchored" data-anchor-id="depression-anxiety-phq-4">7.2. Depression &amp; Anxiety (PHQ-4)</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Depression</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>aov_dep_phq <span class="ot">&lt;-</span> <span class="fu">aov</span>(PHQ4_Depression <span class="sc">~</span> Clusters, <span class="at">data =</span> mega_df)</span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(aov_dep_phq)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>              Df Sum Sq Mean Sq F value Pr(&gt;F)    
Clusters       2  200.3  100.15   57.05 &lt;2e-16 ***
Residuals   1127 1978.4    1.76                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
559 observations deleted due to missingness</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">eta_squared</span>(aov_dep_phq)  <span class="co"># effect size</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>For one-way between subjects designs, partial eta squared is equivalent
  to eta squared. Returning eta squared.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># Effect Size for ANOVA

Parameter | Eta2 |       95% CI
-------------------------------
Clusters  | 0.09 | [0.07, 1.00]

- One-sided CIs: upper bound fixed at [1.00].</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Anxiety</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>aov_anx_phq <span class="ot">&lt;-</span> <span class="fu">aov</span>(PHQ4_Anxiety <span class="sc">~</span> Clusters, <span class="at">data =</span> mega_df)</span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(aov_anx_phq)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>              Df Sum Sq Mean Sq F value Pr(&gt;F)    
Clusters       2  359.3  179.65   79.34 &lt;2e-16 ***
Residuals   1127 2551.9    2.26                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
559 observations deleted due to missingness</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">eta_squared</span>(aov_anx_phq)  <span class="co"># effect size</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>For one-way between subjects designs, partial eta squared is equivalent
  to eta squared. Returning eta squared.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># Effect Size for ANOVA

Parameter | Eta2 |       95% CI
-------------------------------
Clusters  | 0.12 | [0.09, 1.00]

- One-sided CIs: upper bound fixed at [1.00].</code></pre>
</div>
</div>
<p>Depression (PHQ-4): F(2, 1127) = 57.05, p &lt; .001 Depression (PHQ-4) scores explain 9% of the variance in cluster membership - medium effect size</p>
<p>Anxiety (PHQ-4): F(2, 1127) = 79.34, p &lt; .001 Anxiety (PHQ-4) scores explain 12% of the variance in cluster membership - medium effect size</p>
</section>
<section id="gender" class="level2">
<h2 class="anchored" data-anchor-id="gender">7.3. Gender</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cramér's V (2x3 table, df =2): small = .07, medium = .21, large = .35</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>gender_df <span class="ot">&lt;-</span> mega_df <span class="sc">|&gt;</span> <span class="fu">filter</span>(Gender <span class="sc">!=</span> <span class="st">"Other"</span>)</span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Chi-square</span></span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a>chi_gend <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(gender_df<span class="sc">$</span>Gender, gender_df<span class="sc">$</span>Clusters)</span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a>chi_gend</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  gender_df$Gender and gender_df$Clusters
X-squared = 48.867, df = 2, p-value = 2.448e-11</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Effect size (Cramér's V)</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cramers_v</span>(<span class="fu">table</span>(gender_df<span class="sc">$</span>Gender, gender_df<span class="sc">$</span>Clusters))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Cramer's V (adj.) |       95% CI
--------------------------------
0.17              | [0.12, 1.00]

- One-sided CIs: upper bound fixed at [1.00].</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Observed frequencies</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>chi_gend<span class="sc">$</span>observed</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                gender_df$Clusters
gender_df$Gender Cluster 1 Cluster 2 Cluster 3
          Female       336       204       379
          Male         373       182       189</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Expected frequencies - check &lt;5</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>chi_gend<span class="sc">$</span>expected</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                gender_df$Clusters
gender_df$Gender Cluster 1 Cluster 2 Cluster 3
          Female  391.8046  213.3097  313.8857
          Male    317.1954  172.6903  254.1143</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Row percentages (% of each gender in each cluster)</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(gender_df<span class="sc">$</span>Gender, gender_df<span class="sc">$</span>Clusters), <span class="at">margin =</span> <span class="dv">1</span>) <span class="sc">*</span> <span class="dv">100</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>        
         Cluster 1 Cluster 2 Cluster 3
  Female  36.56148  22.19804  41.24048
  Male    50.13441  24.46237  25.40323</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Column percentages (% of each cluster that is each gender)</span></span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(gender_df<span class="sc">$</span>Gender, gender_df<span class="sc">$</span>Clusters), <span class="at">margin =</span> <span class="dv">2</span>) <span class="sc">*</span> <span class="dv">100</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>        
         Cluster 1 Cluster 2 Cluster 3
  Female  47.39069  52.84974  66.72535
  Male    52.60931  47.15026  33.27465</code></pre>
</div>
</div>
<p>χ²(2) = 48.87, p &lt; .001 Small-medium association - Cramér’s V = 0.17</p>
</section>
<section id="mental-health-conditions-diagnosed" class="level2">
<h2 class="anchored" data-anchor-id="mental-health-conditions-diagnosed">7.4. Mental Health Conditions (Diagnosed)</h2>
<section id="mood" class="level3">
<h3 class="anchored" data-anchor-id="mood">7.4.1. Mood</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove NAs</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>mood_df <span class="ot">&lt;-</span> mega_df <span class="sc">|&gt;</span> </span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Disorders_Psychiatric_Mood))</span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Chi-square</span></span>
<span id="cb86-6"><a href="#cb86-6" aria-hidden="true" tabindex="-1"></a>chi_mood <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(mood_df<span class="sc">$</span>Disorders_Psychiatric_Mood, mood_df<span class="sc">$</span>Clusters)</span>
<span id="cb86-7"><a href="#cb86-7" aria-hidden="true" tabindex="-1"></a>chi_mood</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  mood_df$Disorders_Psychiatric_Mood and mood_df$Clusters
X-squared = 35.345, df = 2, p-value = 2.113e-08</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Effect size (Cramér's V)</span></span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cramers_v</span>(<span class="fu">table</span>(mood_df<span class="sc">$</span>Disorders_Psychiatric_Mood, mood_df<span class="sc">$</span>Clusters))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Cramer's V (adj.) |       95% CI
--------------------------------
0.20              | [0.14, 1.00]

- One-sided CIs: upper bound fixed at [1.00].</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Observed frequencies</span></span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>chi_mood<span class="sc">$</span>observed</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       mood_df$Clusters
        Cluster 1 Cluster 2 Cluster 3
  FALSE       299       138       236
  TRUE         30        26        86</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Expected frequencies - check &lt;5</span></span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>chi_mood<span class="sc">$</span>expected</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       mood_df$Clusters
        Cluster 1 Cluster 2 Cluster 3
  FALSE  271.6773 135.42577 265.89693
  TRUE    57.3227  28.57423  56.10307</code></pre>
</div>
</div>
<p>χ²(2) = 35.35, p &lt; .001 Medium association - Cramér’s V = 0.20</p>
</section>
<section id="anxiety" class="level3">
<h3 class="anchored" data-anchor-id="anxiety">7.4.2. Anxiety</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove NAs</span></span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>anxiety_df <span class="ot">&lt;-</span> mega_df <span class="sc">|&gt;</span> </span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Disorders_Psychiatric_Anxiety))</span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-5"><a href="#cb94-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Chi-square</span></span>
<span id="cb94-6"><a href="#cb94-6" aria-hidden="true" tabindex="-1"></a>chi_anxiety <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(anxiety_df<span class="sc">$</span>Disorders_Psychiatric_Anxiety, anxiety_df<span class="sc">$</span>Clusters)</span>
<span id="cb94-7"><a href="#cb94-7" aria-hidden="true" tabindex="-1"></a>chi_anxiety</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  anxiety_df$Disorders_Psychiatric_Anxiety and anxiety_df$Clusters
X-squared = 23.765, df = 2, p-value = 6.91e-06</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Effect size (Cramér's V)</span></span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cramers_v</span>(<span class="fu">table</span>(anxiety_df<span class="sc">$</span>Disorders_Psychiatric_Anxiety, anxiety_df<span class="sc">$</span>Clusters))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Cramer's V (adj.) |       95% CI
--------------------------------
0.16              | [0.10, 1.00]

- One-sided CIs: upper bound fixed at [1.00].</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Observed frequencies</span></span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a>chi_anxiety<span class="sc">$</span>observed</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       anxiety_df$Clusters
        Cluster 1 Cluster 2 Cluster 3
  FALSE       289       138       236
  TRUE         40        26        86</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Expected frequencies - check &lt;5</span></span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a>chi_anxiety<span class="sc">$</span>expected</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       anxiety_df$Clusters
        Cluster 1 Cluster 2 Cluster 3
  FALSE 267.64049  133.4135 261.94601
  TRUE   61.35951   30.5865  60.05399</code></pre>
</div>
</div>
<p>χ²(2) = 23.77, p &lt; .001 Small-medium association - Cramér’s V = 0.16</p>
</section>
<section id="eating-disorders" class="level3">
<h3 class="anchored" data-anchor-id="eating-disorders">7.4.3. Eating Disorders</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove NAs</span></span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a>eating_df <span class="ot">&lt;-</span> mega_df <span class="sc">|&gt;</span> </span>
<span id="cb102-3"><a href="#cb102-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Disorders_Psychiatric_Eating))</span>
<span id="cb102-4"><a href="#cb102-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb102-5"><a href="#cb102-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Chi-square</span></span>
<span id="cb102-6"><a href="#cb102-6" aria-hidden="true" tabindex="-1"></a>chi_eating <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(eating_df<span class="sc">$</span>Disorders_Psychiatric_Eating, eating_df<span class="sc">$</span>Clusters)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in chisq.test(eating_df$Disorders_Psychiatric_Eating,
eating_df$Clusters): Chi-squared approximation may be incorrect</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a>chi_eating</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  eating_df$Disorders_Psychiatric_Eating and eating_df$Clusters
X-squared = 10.187, df = 2, p-value = 0.006137</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Effect size (Cramér's V)</span></span>
<span id="cb106-2"><a href="#cb106-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cramers_v</span>(<span class="fu">table</span>(eating_df<span class="sc">$</span>Disorders_Psychiatric_Eating, eating_df<span class="sc">$</span>Clusters))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Cramer's V (adj.) |       95% CI
--------------------------------
0.10              | [0.00, 1.00]

- One-sided CIs: upper bound fixed at [1.00].</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Observed frequencies</span></span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a>chi_eating<span class="sc">$</span>observed</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       eating_df$Clusters
        Cluster 1 Cluster 2 Cluster 3
  FALSE       324       162       305
  TRUE          5         2        17</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Expected frequencies - check &lt;5</span></span>
<span id="cb110-2"><a href="#cb110-2" aria-hidden="true" tabindex="-1"></a>chi_eating<span class="sc">$</span>expected</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       eating_df$Clusters
         Cluster 1  Cluster 2  Cluster 3
  FALSE 319.311656 159.170552 312.517791
  TRUE    9.688344   4.829448   9.482209</code></pre>
</div>
</div>
<p>χ²(2) = 10.19, p = .006 Small association - Cramér’s V = 0.10 However, 1 expected cell was below 5 (Cluster 2, True, 4.83)</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fisher.test</span>(<span class="fu">table</span>(eating_df<span class="sc">$</span>Disorders_Psychiatric_Eating, eating_df<span class="sc">$</span>Clusters), </span>
<span id="cb112-2"><a href="#cb112-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">simulate.p.value =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Fisher's Exact Test for Count Data with simulated p-value (based on
    2000 replicates)

data:  table(eating_df$Disorders_Psychiatric_Eating, eating_df$Clusters)
p-value = 0.008496
alternative hypothesis: two.sided</code></pre>
</div>
</div>
<p>Due to small expected cell frequencies, Fisher’s exact test was used in place of chi-square. There was a significant association between eating disorder diagnosis and cluster membership (p = .009), though the effect was small (Cramér’s V = 0.10). Eating disorders were disproportionately represented in Cluster 3.</p>
</section>
<section id="autism" class="level3">
<h3 class="anchored" data-anchor-id="autism">7.4.4 Autism</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove NAs</span></span>
<span id="cb114-2"><a href="#cb114-2" aria-hidden="true" tabindex="-1"></a>autism_df <span class="ot">&lt;-</span> mega_df <span class="sc">|&gt;</span> </span>
<span id="cb114-3"><a href="#cb114-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Disorders_Psychiatric_Autism))</span>
<span id="cb114-4"><a href="#cb114-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb114-5"><a href="#cb114-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Chi-square</span></span>
<span id="cb114-6"><a href="#cb114-6" aria-hidden="true" tabindex="-1"></a>chi_autism <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(autism_df<span class="sc">$</span>Disorders_Psychiatric_Autism, autism_df<span class="sc">$</span>Clusters)</span>
<span id="cb114-7"><a href="#cb114-7" aria-hidden="true" tabindex="-1"></a>chi_autism</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  autism_df$Disorders_Psychiatric_Autism and autism_df$Clusters
X-squared = 21.533, df = 2, p-value = 2.11e-05</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Effect size (Cramér's V)</span></span>
<span id="cb116-2"><a href="#cb116-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cramers_v</span>(<span class="fu">table</span>(autism_df<span class="sc">$</span>Disorders_Psychiatric_Autism, autism_df<span class="sc">$</span>Clusters))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Cramer's V (adj.) |       95% CI
--------------------------------
0.15              | [0.09, 1.00]

- One-sided CIs: upper bound fixed at [1.00].</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb118"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Observed frequencies</span></span>
<span id="cb118-2"><a href="#cb118-2" aria-hidden="true" tabindex="-1"></a>chi_autism<span class="sc">$</span>observed</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       autism_df$Clusters
        Cluster 1 Cluster 2 Cluster 3
  FALSE       315       159       282
  TRUE         14         5        40</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Expected frequencies - check &lt;5</span></span>
<span id="cb120-2"><a href="#cb120-2" aria-hidden="true" tabindex="-1"></a>chi_autism<span class="sc">$</span>expected</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       autism_df$Clusters
        Cluster 1 Cluster 2 Cluster 3
  FALSE 305.18282 152.12761 298.68957
  TRUE   23.81718  11.87239  23.31043</code></pre>
</div>
</div>
<p>χ²(2) = 21.53, p &lt; .001 Small-medium association - Cramér’s V = 0.15</p>
</section>
<section id="adhd" class="level3">
<h3 class="anchored" data-anchor-id="adhd">7.4.5. ADHD</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb122"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove NAs</span></span>
<span id="cb122-2"><a href="#cb122-2" aria-hidden="true" tabindex="-1"></a>adhd_df <span class="ot">&lt;-</span> mega_df <span class="sc">|&gt;</span> </span>
<span id="cb122-3"><a href="#cb122-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Disorders_Psychiatric_ADHD))</span>
<span id="cb122-4"><a href="#cb122-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb122-5"><a href="#cb122-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Chi-square</span></span>
<span id="cb122-6"><a href="#cb122-6" aria-hidden="true" tabindex="-1"></a>chi_adhd <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(adhd_df<span class="sc">$</span>Disorders_Psychiatric_ADHD, adhd_df<span class="sc">$</span>Clusters)</span>
<span id="cb122-7"><a href="#cb122-7" aria-hidden="true" tabindex="-1"></a>chi_adhd</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  adhd_df$Disorders_Psychiatric_ADHD and adhd_df$Clusters
X-squared = 13.071, df = 2, p-value = 0.001451</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb124"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb124-1"><a href="#cb124-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Effect size (Cramér's V)</span></span>
<span id="cb124-2"><a href="#cb124-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cramers_v</span>(<span class="fu">table</span>(adhd_df<span class="sc">$</span>Disorders_Psychiatric_ADHD, adhd_df<span class="sc">$</span>Clusters))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Cramer's V (adj.) |       95% CI
--------------------------------
0.12              | [0.04, 1.00]

- One-sided CIs: upper bound fixed at [1.00].</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb126"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb126-1"><a href="#cb126-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Observed frequencies</span></span>
<span id="cb126-2"><a href="#cb126-2" aria-hidden="true" tabindex="-1"></a>chi_adhd<span class="sc">$</span>observed</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       adhd_df$Clusters
        Cluster 1 Cluster 2 Cluster 3
  FALSE       311       150       278
  TRUE         18        14        44</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb128"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb128-1"><a href="#cb128-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Expected frequencies - check for &lt;5</span></span>
<span id="cb128-2"><a href="#cb128-2" aria-hidden="true" tabindex="-1"></a>chi_adhd<span class="sc">$</span>expected</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       adhd_df$Clusters
        Cluster 1 Cluster 2 Cluster 3
  FALSE 298.32025 148.70675 291.97301
  TRUE   30.67975  15.29325  30.02699</code></pre>
</div>
</div>
<p>χ²(2) = 13.07, p = .001 Small association - Cramér’s V = 0.12</p>
</section>
</section>
<section id="somatic-health-conditions-diagnosed" class="level2">
<h2 class="anchored" data-anchor-id="somatic-health-conditions-diagnosed">7.5. Somatic Health Conditions (Diagnosed)</h2>
<section id="afferent-sensitivity" class="level3">
<h3 class="anchored" data-anchor-id="afferent-sensitivity">7.5.1. Afferent Sensitivity</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb130"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb130-1"><a href="#cb130-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove NAs</span></span>
<span id="cb130-2"><a href="#cb130-2" aria-hidden="true" tabindex="-1"></a>as_df <span class="ot">&lt;-</span> mega_df <span class="sc">|&gt;</span> </span>
<span id="cb130-3"><a href="#cb130-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Disorders_Somatic_AfferentSensitivity))</span>
<span id="cb130-4"><a href="#cb130-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb130-5"><a href="#cb130-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Chi-square</span></span>
<span id="cb130-6"><a href="#cb130-6" aria-hidden="true" tabindex="-1"></a>chi_as <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(as_df<span class="sc">$</span>Disorders_Somatic_AfferentSensitivity, as_df<span class="sc">$</span>Clusters)</span>
<span id="cb130-7"><a href="#cb130-7" aria-hidden="true" tabindex="-1"></a>chi_as</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  as_df$Disorders_Somatic_AfferentSensitivity and as_df$Clusters
X-squared = 19.387, df = 2, p-value = 6.169e-05</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb132"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb132-1"><a href="#cb132-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Effect size (Cramér's V)</span></span>
<span id="cb132-2"><a href="#cb132-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cramers_v</span>(<span class="fu">table</span>(as_df<span class="sc">$</span>Disorders_Somatic_AfferentSensitivity, as_df<span class="sc">$</span>Clusters))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Cramer's V (adj.) |       95% CI
--------------------------------
0.15              | [0.08, 1.00]

- One-sided CIs: upper bound fixed at [1.00].</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb134"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb134-1"><a href="#cb134-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Observed frequencies</span></span>
<span id="cb134-2"><a href="#cb134-2" aria-hidden="true" tabindex="-1"></a>chi_as<span class="sc">$</span>observed</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       as_df$Clusters
        Cluster 1 Cluster 2 Cluster 3
  FALSE       284       130       233
  TRUE         45        34        89</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb136"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb136-1"><a href="#cb136-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Expected frequencies - check for &lt;5</span></span>
<span id="cb136-2"><a href="#cb136-2" aria-hidden="true" tabindex="-1"></a>chi_as<span class="sc">$</span>expected</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       as_df$Clusters
        Cluster 1 Cluster 2 Cluster 3
  FALSE  261.1816 130.19387 255.62454
  TRUE    67.8184  33.80613  66.37546</code></pre>
</div>
</div>
<p>χ²(2) = 19.39, p &lt; .001 Small-medium association - Cramér’s V = 0.15</p>
</section>
<section id="central-sensitisation" class="level3">
<h3 class="anchored" data-anchor-id="central-sensitisation">7.5.2. Central Sensitisation</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb138"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb138-1"><a href="#cb138-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove NAs</span></span>
<span id="cb138-2"><a href="#cb138-2" aria-hidden="true" tabindex="-1"></a>cs_df <span class="ot">&lt;-</span> mega_df <span class="sc">|&gt;</span> </span>
<span id="cb138-3"><a href="#cb138-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Disorders_Somatic_CentralSensitization))</span>
<span id="cb138-4"><a href="#cb138-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb138-5"><a href="#cb138-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Chi-square</span></span>
<span id="cb138-6"><a href="#cb138-6" aria-hidden="true" tabindex="-1"></a>chi_cs <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(cs_df<span class="sc">$</span>Disorders_Somatic_CentralSensitization, cs_df<span class="sc">$</span>Clusters)</span>
<span id="cb138-7"><a href="#cb138-7" aria-hidden="true" tabindex="-1"></a>chi_cs</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  cs_df$Disorders_Somatic_CentralSensitization and cs_df$Clusters
X-squared = 12.918, df = 2, p-value = 0.001566</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb140"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb140-1"><a href="#cb140-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Effect size (Cramér's V)</span></span>
<span id="cb140-2"><a href="#cb140-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cramers_v</span>(<span class="fu">table</span>(cs_df<span class="sc">$</span>Disorders_Somatic_CentralSensitization, cs_df<span class="sc">$</span>Clusters))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Cramer's V (adj.) |       95% CI
--------------------------------
0.12              | [0.04, 1.00]

- One-sided CIs: upper bound fixed at [1.00].</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb142"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb142-1"><a href="#cb142-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Observed frequencies</span></span>
<span id="cb142-2"><a href="#cb142-2" aria-hidden="true" tabindex="-1"></a>chi_cs<span class="sc">$</span>observed</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       cs_df$Clusters
        Cluster 1 Cluster 2 Cluster 3
  FALSE       262       116       217
  TRUE         67        48       105</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb144"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb144-1"><a href="#cb144-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Expected frequencies - check for &lt;5</span></span>
<span id="cb144-2"><a href="#cb144-2" aria-hidden="true" tabindex="-1"></a>chi_cs<span class="sc">$</span>expected</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       cs_df$Clusters
        Cluster 1 Cluster 2 Cluster 3
  FALSE 240.19018 119.73006 235.07975
  TRUE   88.80982  44.26994  86.92025</code></pre>
</div>
</div>
<p>χ²(2) = 12.92, p = .002 Small association - Cramér’s V = 0.12</p>
</section>
<section id="autonomic-dysfunction" class="level3">
<h3 class="anchored" data-anchor-id="autonomic-dysfunction">7.5.3. Autonomic Dysfunction</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb146"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb146-1"><a href="#cb146-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove NAs</span></span>
<span id="cb146-2"><a href="#cb146-2" aria-hidden="true" tabindex="-1"></a>ad_df <span class="ot">&lt;-</span> mega_df <span class="sc">|&gt;</span> </span>
<span id="cb146-3"><a href="#cb146-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Disorders_Somatic_AutonomicDysfunction))</span>
<span id="cb146-4"><a href="#cb146-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb146-5"><a href="#cb146-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Chi-square</span></span>
<span id="cb146-6"><a href="#cb146-6" aria-hidden="true" tabindex="-1"></a>chi_ad <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(ad_df<span class="sc">$</span>Disorders_Somatic_AutonomicDysfunction, ad_df<span class="sc">$</span>Clusters)</span>
<span id="cb146-7"><a href="#cb146-7" aria-hidden="true" tabindex="-1"></a>chi_ad</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  ad_df$Disorders_Somatic_AutonomicDysfunction and ad_df$Clusters
X-squared = 6.6996, df = 2, p-value = 0.03509</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb148"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb148-1"><a href="#cb148-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Effect size (Cramér's V)</span></span>
<span id="cb148-2"><a href="#cb148-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cramers_v</span>(<span class="fu">table</span>(ad_df<span class="sc">$</span>Disorders_Somatic_AutonomicDysfunction, ad_df<span class="sc">$</span>Clusters))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Cramer's V (adj.) |       95% CI
--------------------------------
0.08              | [0.00, 1.00]

- One-sided CIs: upper bound fixed at [1.00].</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb150"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb150-1"><a href="#cb150-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Observed frequencies</span></span>
<span id="cb150-2"><a href="#cb150-2" aria-hidden="true" tabindex="-1"></a>chi_ad<span class="sc">$</span>observed</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       ad_df$Clusters
        Cluster 1 Cluster 2 Cluster 3
  FALSE       282       132       251
  TRUE         47        32        71</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb152"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb152-1"><a href="#cb152-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Expected frequencies - check for &lt;5</span></span>
<span id="cb152-2"><a href="#cb152-2" aria-hidden="true" tabindex="-1"></a>chi_ad<span class="sc">$</span>expected</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       ad_df$Clusters
        Cluster 1 Cluster 2 Cluster 3
  FALSE 268.44785 133.81595  262.7362
  TRUE   60.55215  30.18405   59.2638</code></pre>
</div>
</div>
<p>χ²(2) = 6.70, p = .035 Small association - Cramér’s V = 0.08</p>
</section>
<section id="immune-inflammatory" class="level3">
<h3 class="anchored" data-anchor-id="immune-inflammatory">7.5.4. Immune-Inflammatory</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb154"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb154-1"><a href="#cb154-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove NAs</span></span>
<span id="cb154-2"><a href="#cb154-2" aria-hidden="true" tabindex="-1"></a>ii_df <span class="ot">&lt;-</span> mega_df <span class="sc">|&gt;</span> </span>
<span id="cb154-3"><a href="#cb154-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Disorders_Somatic_ImmuneInflammatory))</span>
<span id="cb154-4"><a href="#cb154-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb154-5"><a href="#cb154-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Chi-square</span></span>
<span id="cb154-6"><a href="#cb154-6" aria-hidden="true" tabindex="-1"></a>chi_ii <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(ii_df<span class="sc">$</span>Disorders_Somatic_ImmuneInflammatory, ii_df<span class="sc">$</span>Clusters)</span>
<span id="cb154-7"><a href="#cb154-7" aria-hidden="true" tabindex="-1"></a>chi_ii</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  ii_df$Disorders_Somatic_ImmuneInflammatory and ii_df$Clusters
X-squared = 22.809, df = 2, p-value = 1.115e-05</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb156"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb156-1"><a href="#cb156-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Effect size (Cramér's V)</span></span>
<span id="cb156-2"><a href="#cb156-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cramers_v</span>(<span class="fu">table</span>(ii_df<span class="sc">$</span>Disorders_Somatic_ImmuneInflammatory, ii_df<span class="sc">$</span>Clusters))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Cramer's V (adj.) |       95% CI
--------------------------------
0.16              | [0.09, 1.00]

- One-sided CIs: upper bound fixed at [1.00].</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb158"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb158-1"><a href="#cb158-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Observed frequencies</span></span>
<span id="cb158-2"><a href="#cb158-2" aria-hidden="true" tabindex="-1"></a>chi_ii<span class="sc">$</span>observed</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       ii_df$Clusters
        Cluster 1 Cluster 2 Cluster 3
  FALSE       255       104       196
  TRUE         74        60       126</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb160"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb160-1"><a href="#cb160-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Expected frequencies - check for &lt;5</span></span>
<span id="cb160-2"><a href="#cb160-2" aria-hidden="true" tabindex="-1"></a>chi_ii<span class="sc">$</span>expected</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       ii_df$Clusters
        Cluster 1 Cluster 2 Cluster 3
  FALSE  224.0429 111.68098  219.2761
  TRUE   104.9571  52.31902  102.7239</code></pre>
</div>
</div>
<p>χ²(2) = 22.81, p &lt; .001 Small-medium association - Cramér’s V = 0.16</p>
</section>
</section>
</section>
<section id="multinomial-logistic-regression" class="level1">
<h1>8. Multinomial Logistic Regression</h1>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb162"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb162-1"><a href="#cb162-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set a reference cluster - what should this be?</span></span>
<span id="cb162-2"><a href="#cb162-2" aria-hidden="true" tabindex="-1"></a>mega_df<span class="sc">$</span>Clusters_relev <span class="ot">&lt;-</span> <span class="fu">relevel</span>(mega_df<span class="sc">$</span>Clusters, <span class="at">ref =</span> <span class="st">"Cluster 1"</span>)</span>
<span id="cb162-3"><a href="#cb162-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb162-4"><a href="#cb162-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Make dummy variable</span></span>
<span id="cb162-5"><a href="#cb162-5" aria-hidden="true" tabindex="-1"></a>mega_df<span class="sc">$</span>Male <span class="ot">&lt;-</span> <span class="fu">rec</span>(mega_df<span class="sc">$</span>Gender, <span class="at">rec =</span> <span class="st">"Male = 1; Female = 0; else = NA"</span>)</span>
<span id="cb162-6"><a href="#cb162-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb162-7"><a href="#cb162-7" aria-hidden="true" tabindex="-1"></a>multinom <span class="ot">&lt;-</span> <span class="fu">multinom</span>(</span>
<span id="cb162-8"><a href="#cb162-8" aria-hidden="true" tabindex="-1"></a>  Clusters_relev <span class="sc">~</span> Age <span class="sc">+</span> PHQ4_Depression <span class="sc">+</span> PHQ4_Anxiety <span class="sc">+</span> Gender <span class="sc">+</span> Disorders_Psychiatric_Mood <span class="sc">+</span> Disorders_Psychiatric_Anxiety <span class="sc">+</span> Disorders_Psychiatric_Eating <span class="sc">+</span> Disorders_Psychiatric_Autism <span class="sc">+</span> Disorders_Psychiatric_ADHD <span class="sc">+</span> Disorders_Somatic_AfferentSensitivity <span class="sc">+</span> Disorders_Somatic_CentralSensitization <span class="sc">+</span> Disorders_Somatic_AutonomicDysfunction <span class="sc">+</span> Disorders_Somatic_ImmuneInflammatory,</span>
<span id="cb162-9"><a href="#cb162-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> mega_df</span>
<span id="cb162-10"><a href="#cb162-10" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># weights:  48 (30 variable)
initial  value 895.369015 
iter  10 value 784.831231
iter  20 value 762.462274
iter  30 value 760.141930
iter  40 value 759.982243
final  value 759.981005 
converged</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb164"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb164-1"><a href="#cb164-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(multinom)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
multinom(formula = Clusters_relev ~ Age + PHQ4_Depression + PHQ4_Anxiety + 
    Gender + Disorders_Psychiatric_Mood + Disorders_Psychiatric_Anxiety + 
    Disorders_Psychiatric_Eating + Disorders_Psychiatric_Autism + 
    Disorders_Psychiatric_ADHD + Disorders_Somatic_AfferentSensitivity + 
    Disorders_Somatic_CentralSensitization + Disorders_Somatic_AutonomicDysfunction + 
    Disorders_Somatic_ImmuneInflammatory, data = mega_df)

Coefficients:
          (Intercept)          Age PHQ4_Depression PHQ4_Anxiety  GenderMale
Cluster 2  -1.3460210  0.002624287     0.009202436    0.2336835 -0.08810532
Cluster 3   0.2073866 -0.029894541     0.161114974    0.2575150 -0.80843517
          GenderOther Disorders_Psychiatric_MoodTRUE
Cluster 2  -13.701837                      0.9432988
Cluster 3   -0.409368                      0.8740235
          Disorders_Psychiatric_AnxietyTRUE Disorders_Psychiatric_EatingTRUE
Cluster 2                        -0.9184226                       -0.7221565
Cluster 3                        -0.7632946                       -0.2783784
          Disorders_Psychiatric_AutismTRUE Disorders_Psychiatric_ADHDTRUE
Cluster 2                       -0.6425992                       0.429047
Cluster 3                        0.4242904                       0.234516
          Disorders_Somatic_AfferentSensitivityTRUE
Cluster 2                                 0.2284066
Cluster 3                                 0.4744193
          Disorders_Somatic_CentralSensitizationTRUE
Cluster 2                                  0.2030625
Cluster 3                                  0.2344068
          Disorders_Somatic_AutonomicDysfunctionTRUE
Cluster 2                                  0.1361853
Cluster 3                                  0.4689828
          Disorders_Somatic_ImmuneInflammatoryTRUE
Cluster 2                                0.4965462
Cluster 3                                0.3871846

Std. Errors:
          (Intercept)         Age PHQ4_Depression PHQ4_Anxiety GenderMale
Cluster 2   0.3383182 0.007146724      0.10503680   0.09498609  0.2019598
Cluster 3   0.2852406 0.006879791      0.08971144   0.08123835  0.1896184
           GenderOther Disorders_Psychiatric_MoodTRUE
Cluster 2 7.713938e-07                      0.5668794
Cluster 3 5.969663e-01                      0.4751050
          Disorders_Psychiatric_AnxietyTRUE Disorders_Psychiatric_EatingTRUE
Cluster 2                         0.5449893                        0.8840548
Cluster 3                         0.4530907                        0.5905574
          Disorders_Psychiatric_AutismTRUE Disorders_Psychiatric_ADHDTRUE
Cluster 2                        0.5541402                      0.4020894
Cluster 3                        0.3579831                      0.3364168
          Disorders_Somatic_AfferentSensitivityTRUE
Cluster 2                                 0.2749745
Cluster 3                                 0.2425011
          Disorders_Somatic_CentralSensitizationTRUE
Cluster 2                                  0.2438375
Cluster 3                                  0.2218356
          Disorders_Somatic_AutonomicDysfunctionTRUE
Cluster 2                                  0.2779647
Cluster 3                                  0.2510090
          Disorders_Somatic_ImmuneInflammatoryTRUE
Cluster 2                                0.2239104
Cluster 3                                0.2043962

Residual Deviance: 1519.962 
AIC: 1579.962 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb166"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb166-1"><a href="#cb166-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(multinom, <span class="at">exponentiate =</span> <span class="cn">TRUE</span>, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)  <span class="co"># odds ratios</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 30 × 8
   y.level   term        estimate std.error statistic p.value conf.low conf.high
   &lt;chr&gt;     &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
 1 Cluster 2 (Intercept)  2.60e-1   3.38e-1  -3.98e+0 6.93e-5  1.34e-1   5.05e-1
 2 Cluster 2 Age          1.00e+0   7.15e-3   3.67e-1 7.13e-1  9.89e-1   1.02e+0
 3 Cluster 2 PHQ4_Depre…  1.01e+0   1.05e-1   8.76e-2 9.30e-1  8.21e-1   1.24e+0
 4 Cluster 2 PHQ4_Anxie…  1.26e+0   9.50e-2   2.46e+0 1.39e-2  1.05e+0   1.52e+0
 5 Cluster 2 GenderMale   9.16e-1   2.02e-1  -4.36e-1 6.63e-1  6.16e-1   1.36e+0
 6 Cluster 2 GenderOther  1.12e-6   7.71e-7  -1.78e+7 0        1.12e-6   1.12e-6
 7 Cluster 2 Disorders_…  2.57e+0   5.67e-1   1.66e+0 9.61e-2  8.46e-1   7.80e+0
 8 Cluster 2 Disorders_…  3.99e-1   5.45e-1  -1.69e+0 9.19e-2  1.37e-1   1.16e+0
 9 Cluster 2 Disorders_…  4.86e-1   8.84e-1  -8.17e-1 4.14e-1  8.59e-2   2.75e+0
10 Cluster 2 Disorders_…  5.26e-1   5.54e-1  -1.16e+0 2.46e-1  1.78e-1   1.56e+0
# ℹ 20 more rows</code></pre>
</div>
</div>
<p>For Cluster 2, higher anxiety symptoms significantly increased the odds of membership (OR = 1.26, p = .014), as did the presence of immune-inflammatory somatic disorders (OR = 1.64, p = .027). No other predictors significantly distinguished Cluster 2 from Cluster 1. For Cluster 3, younger age was associated with greater odds of membership (OR = 0.97, p &lt; .001). Higher anxiety symptoms also predicted Cluster 3 membership (OR = 1.29, p = .002), and men were less likely than women to belong to this cluster (OR = 0.45, p &lt; .001). Several additional predictors showed marginal associations (ps = .050–.073) but were not significant.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>